ibm-openbmc/pldm

common/flight_recorder.hpp
common/utils.cpp
common/utils.hpp
host-bmc/host_pdr_handler.cpp
requester/request.hpp

This PR fixes the flight recorder crash and also adds the time stamp in the flight recorder.
This is up streamed in the following commits :
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45362/16
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45811/4

Flight recorder fix

---

oem/ibm/libpldmresponder/file_io_type_cert.cpp
oem/ibm/requester/dbus_to_file_handler.cpp

Signed-off-by: Varsha Kaverappa <vkaverap@in.ibm.com>
Change-Id: I20fb11581cab6a750b092173ba61aeae47e9ab52

 Debug trace added for VMI no connection issue

---

configurations/pdr/11.json
configurations/pdr/4.json
oem/ibm/libpldmresponder/oem_ibm_handler.cpp

This commit adds change to the container IDs of few PDRs
which had 0 as container ID in the current PDR repository.
Change-Id: Ia390054580b14bde736a3360fe029fd767da227f

pldm: Change Container IDs of Sensors and Effecters

---

host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp
libpldm/pdr.c
libpldm/pdr.h

Fixes for the PLDM crash during RR

---

common/utils.cpp
host-bmc/host_pdr_handler.cpp
oem/ibm/libpldmresponder/file_io.hpp

- This PR would fix crashes in various paths like dump,
COD license paths including the VMI certificate exchange.
- This PR would also fix the crash that happens when the host
off signal is received.

Fix crashes and potential crashes

---

libpldm/meson.build
oem/ibm/configurations/bios/string_attrs.json
oem/ibm/libpldm/state_set_oem_ibm.h
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

defect SW536592 - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48754
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48788
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/47837

Pldm defect fix sbe bios reboot effecter

---

pldmtool/oem/ibm/oem_ibm_state_set.hpp

Fix for missing file change in PLDM bump

---

oem/ibm/configurations/bios/enum_attrs.json
oem/ibm/libpldmresponder/inband_code_update.cpp
oem/ibm/libpldmresponder/inband_code_update.hpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45387
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44735

Pldm next boot side boot side bios attr changes

---

oem/ibm/libpldmresponder/oem_ibm_handler.cpp

https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45751
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45925/

Pldm Inband Code rename event support and  boot side effecter removal

---

host-bmc/host_pdr_handler.cpp
libpldmresponder/base.cpp
libpldmresponder/platform.cpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/requester/dbus_to_file_handler.cpp
oem/ibm/requester/dbus_to_file_handler.hpp

Signed-off-by: Varsha Kaverappa <vkaverap@in.ibm.com>

Fix for SW539617

---

configurations/pdr/11.json
libpldmresponder/bios_config.cpp
libpldmresponder/platform_numeric_effecter.hpp
oem/ibm/configurations/bios/enum_attrs.json

SW536591 - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48003
SW538901 - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48816
setBiosTable trace removal - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49055

Pldm numeric effecter bios trac remv tpm enable

---

oem/ibm/configurations/fru/Fan_VINI.json

add support for fan fru VINI record and remove battery
VINI record since battery does not have vpd
Change-Id: I031417f102241890c42d51234991c322e4433343
Signed-off-by: Sampa Misra <sampmisr@in.ibm.com>

oem: refine support for VINI record

---

libpldmresponder/fru.hpp

Change-Id: Ifb93e71d38ee5186966c992c40653b1edaf6fdb7

PLDM: Panel hotplug support

---

common/test/pldm_utils_test.cpp
common/utils.cpp
common/utils.hpp
configurations/host/host_fru_associations.json
host-bmc/custom_dbus.cpp
host-bmc/custom_dbus.hpp
host-bmc/dbus_to_event_handler.cpp
host-bmc/host_associations_parser.cpp
host-bmc/host_associations_parser.hpp
host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp
libpldm/pdr.c
libpldm/pdr.h
libpldm/tests/libpldm_pdr_test.cpp

This PR would bring in the necessary dynamic association
support for multiple mex drawers at runtime.
This PR would also fix SW536890.

Multi mex support & fix SW536890

---

oem/ibm/configurations/bios/enum_attrs.json

Fix for bootside attributes removal during rebase

---

configurations/pdr/11.json
host-bmc/custom_dbus.cpp
host-bmc/custom_dbus.hpp
host-bmc/host_pdr_handler.cpp
libpldm/fru.c
libpldm/fru.h
libpldmresponder/bios_config.cpp
oem/ibm/libpldmresponder/collect_slot_vpd.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp

This PR also Include :
1. fix for SW533812 (https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49089)
2. fix for error (Unknown D-Bus property type, TYPE=Functional) - (https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48841)
3. safe variant for fru record table (https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/47354)
4. Remove unwanted traces

Mex health roll up support

---

common/utils.cpp
common/utils.hpp
host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp
libpldmresponder/oem_handler.hpp
libpldmresponder/pdr_utils.cpp
libpldmresponder/pdr_utils.hpp
libpldmresponder/platform.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

Pldm fix for op panel multi function support
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48950/2

Pldm op panel multi function fix

---

oem/ibm/libpldm/file_io.c
oem/ibm/libpldm/file_io.h
oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/file_io.hpp
oem/ibm/libpldmresponder/file_io_by_type.hpp
oem/ibm/libpldmresponder/file_io_type_cert.hpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/file_io_type_dump.hpp
oem/ibm/libpldmresponder/file_io_type_lic.cpp
oem/ibm/libpldmresponder/file_io_type_lic.hpp
oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/file_io_type_pel.hpp
oem/ibm/libpldmresponder/file_io_type_progress_src.hpp
oem/ibm/requester/dbus_to_file_handler.cpp
oem/ibm/test/libpldm_fileio_test.cpp

Upstream commits - 
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45156/7
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49166/5
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49211/3
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49404/3

Resource dump authentication support

---

host-bmc/host_pdr_handler.hpp

Fix for PLDM Bump CI failure

---

common/utils.cpp
common/utils.hpp
host-bmc/host_pdr_handler.cpp
libpldmresponder/oem_handler.hpp
oem/ibm/configurations/bios/enum_attrs.json
oem/ibm/libpldmresponder/inband_code_update.cpp
oem/ibm/libpldmresponder/inband_code_update.hpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp
softoff/softoff.cpp

https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/47836/6
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/49472/9

Pldm Boot types and APR setting

---

oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json
oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json

PLDM PDR: Add support for IOSCM rainier 1S-4U

---

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

Pldm RR crash fix

---

oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/inband_code_update.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

PLDM Fix for bootside attribute defect

---

oem/ibm/libpldmresponder/inband_code_update.cpp
pldmd/pldmd.cpp

PLDM bootside bump failure fix

---

libpldmresponder/platform.cpp

Witherspoon-tacoma systems does not run entity manager,
so pldm will not be able to get the system type , in that
case make sure we build the common PDR's & dont send the
PLDM_ERROR_NOTREADY to hypervisor.
Fixes : SW541941

Don't wait to determine system type PLDM

---

libpldmresponder/fru.cpp
libpldmresponder/fru.hpp

This commit fixes the defect - SW538837

PLDM: Fix for error logs logged in BMC after factory reset.

---

libpldm/pdr.c
libpldmresponder/fru.cpp
oem/ibm/libpldmresponder/collect_slot_vpd.cpp
oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/utils.cpp

This commit has the following changes:
1. Added and improved ffdc in system and resource dump paths
2. Removed the unwanted traces
Change-Id: I807246a177c6d956c07612221c38c17f6193f140

pldm: FFDC enhancement

---

libpldmresponder/fru.cpp

This commit fixes and removes some error traces when
doing the CM operation and also fixes some minor errors.

PLDM: fix some error traces

---

host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp

This reverts commit 790c2757661172260ee11c62000d9cd1afd3bbb1.

Revert "Fetch Hostboot sensor status from HBRT (#126)"

---

libpldmresponder/fru.cpp

The pad bytes where getting added everytime we build
the FRU table this was leading to a pldmtool crash after
each CM operation.
This commit adds the padBytes only when a GetFRURecordTable
is called.

fix the fru record table

---

oem/ibm/configurations/bios/enum_attrs.json

PLDM: Change default value for pvm_rtad bios attribute

---

oem/ibm/configurations/bios/enum_attrs.json

Change-Id: I81551c0525fc6c68d76e9054b8f2f9d1c50644bd

bios : Add Default value for the pvm_default_os_type attribute

---

common/utils.cpp
host-bmc/host_pdr_handler.cpp

This commit adds some trace lines to the code.

Add debug information

---

oem/ibm/libpldmresponder/inband_code_update.cpp

During a rename, set the next boot side to Perm (same as current) so
that in case of a failed update, PHYP knows to boot from the Perm side.
The next boot side would be set to Temp on a successful update (via the
Priority callback function).
Update the next boot side attribute (fw_boot_side) whenever the next
boot side value is set or changed so that in error scenarios, PHYP knows
which side to boot from.
Setting fw_boot_side attribute automatically calls the function to set
the next boot side because the attribute can be also be set externally
by PHYP, therefore check the requested next boot side already has the
highest priority, in which case there's no need to set the Priority.
Also checking the current priority allows to catch if the alternate
version may not exist because of a code …

oem: ibm: Set next boot side attribute

---

oem/ibm/configurations/bios/enum_attrs.json

This reverts commit 39ca54a676ba323b93be099065f1c650526d4276.

Revert "Revert "bios : Add Default value for the pvm_default_os_type""

---

oem/ibm/configurations/bios/enum_attrs.json
oem/ibm/configurations/bios/integer_attrs.json

oem-ibm: Add  new bios attrs in enum, integer attribute json

---

oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/file_io_by_type.hpp
oem/ibm/libpldmresponder/file_io_type_cert.cpp
oem/ibm/libpldmresponder/file_io_type_cert.hpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/file_io_type_dump.hpp
oem/ibm/libpldmresponder/file_io_type_lic.cpp
oem/ibm/libpldmresponder/file_io_type_lic.hpp
oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/file_io_type_pel.hpp
oem/ibm/libpldmresponder/file_io_type_progress_src.hpp

Defect: [SW514399](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW514399)

Pldm vmi error codes

---

oem/ibm/libpldmresponder/file_io_type_cert.hpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/file_io_type_dump.hpp
oem/ibm/requester/dbus_to_file_handler.cpp

This commit is to update the status codes reported
by host during the creation of resource dump.
Defect: SW521505

PLDM: Resource Dump status Codes

---

oem/ibm/configurations/pdr/ibm,everest/11.json
oem/ibm/configurations/pdr/ibm,everest/4.json

Fixed Json changes related to Tod_Battery and PCIeSlot9

---

oem/ibm/libpldmresponder/inband_code_update.cpp

This commit is to fix the bootside rename
defect:  SW544814 in the out of band code
update path.

PLDM: Fix code update Rename

---

oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

PLDM should not honor FILE IO read/write with 0 byte

---

oem/ibm/configurations/bios/integer_attrs.json

Modify the helpText for hb_field_core_override

---

host-bmc/host_pdr_handler.cpp

PLDM: FFDC enhancement in the R/R Path

---

oem/ibm/libpldmresponder/utils.cpp
oem/ibm/requester/dbus_to_file_handler.cpp

This commit fixes the defects SW548966 and SW544557

PLDM: Fixes for SW548966 and SW544557

---

host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp

This reverts commit f6ed9a6e6a7797ae8efe454309d410af92288a8b.

Revert "Revert "Fetch Hostboot sensor status from HBRT (#126)" (#129)"

---

oem/ibm/configurations/fru/Chassis_VCEN.json
oem/ibm/configurations/fru/Motherboard_VCEN.json

oem-fru : Add VCEN fru records in BMC Fru record table

---

oem/ibm/libpldmresponder/inband_code_update.cpp

The mksquashfs command adds data to the header such as the creation
time, this makes the generated squashfs image not match the one
generated by the build. Use additional options offered by the squashfs
tools for reproducible builds such as setting the timestamp to 0
(reference:
https://lore.kernel.org/lkml/CAB3wodcL=gnQOmHGGNukWK3OUbU2p=OHzLmzPi7ns_WNTGBEwg@mail.gmail.com/)
Also specify the permissions (777 for the directory to allow any BMC
user name to access this directory to write the lids), and 440 for the
lid files as these files are intended to be read-only, for cases the
root filesystem on the BMC is not read-only.
Tested: Verified the generated image was identical to one generated
during a build process.
Change-Id: Id3aeebafad2395bbf715a701c8592cd6939f57bf
Signed-off-by: Adriana …

oem: ibm: Add squashfs options for reproducible builds

---

host-bmc/host_pdr_handler.cpp

- After the PDR exchange from host post reset reload, bmc
would start asking for the host sensor states and update
the dbus objects.
- There was a bug in code where the iterator was crossing
the end - causing a bad_alloc failure, it is manifested as
either pldm crash or an oom condition(where the recursion
is never completed and the stack keeps growing).
Testedby:
1. with the patch on rain139bmc, did 10 power on/offs & also
reset reload's when host is up and did not see any issue.

Fix oom condition & pldm crash in resetreload path

---

host-bmc/dbus_to_host_effecters.cpp
host-bmc/host_pdr_handler.cpp
libpldmresponder/fru.cpp
libpldmresponder/platform.cpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/requester/dbus_to_file_handler.cpp
softoff/main.cpp

PLDM:PelSeverity: Change the syntax format.

---

oem/ibm/configurations/bios/enum_attrs.json

bios:Add pvm_clear_nvram bios attribute

---

common/utils.cpp

Changes to persist the CPU core count and DIMM
Operational status across reboots when host is powered
off.
Defect:SW550463

PLDM: FCO and DIMM D-bus Objects persistency

---

libpldm/pdr.c
oem/ibm/configurations/pdr/ibm,rainier-2u/11.json

Resolved nullptr dereference errors.

[PLDM] Resolved nullptr dereference errors in PLDM

---

host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp
libpldmresponder/oem_handler.hpp
libpldmresponder/platform.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp

This reverts commit 606c6a86406f38b3af21001aa91a711f4898572b.

Revert "PLDM: Changes to persist the HB PDRs in the repo before merging (#298)"

---

libpldmresponder/bios.cpp

The BMC will have the correct time when in NTP mode, so we don't need to try and set the time again which may cause potential time drifts.
Tested: Using pldmtool
Change-Id: I8ab99f6ab44564a752fa844e9abaeef643ef417b

PLDM : Changes in setDateTime command

---

oem/ibm/configurations/fileTable.json

Add the new Planar SPD lid files for platforms.
Signed-off-by: Deb McLemore <debmc@us.ibm.com>

Hostboot Add Planar SPD lid files for platforms

---

common/utils.hpp
host-bmc/test/custom_dbus_test.cpp
host-bmc/test/meson.build
host-bmc/test/utils_test.cpp
libpldmresponder/fru.cpp
oem/ibm/libpldmresponder/inband_code_update.cpp
oem/ibm/requester/dbus_to_file_handler.cpp

This commit makes some changes to the 1050 branch according to the 1030 branch.
The changes made were part of features and 
defect solutions missed in the 1050 branch.
The potentially impacted features without these changes would be CEC CM and MEX CM.

PLDM:1050 - Missed changes

---

oem/ibm/configurations/bios/enum_attrs.json
oem/ibm/configurations/bios/integer_attrs.json
oem/ibm/configurations/bios/string_attrs.json

RTC: 209572
STGD:411700
Change-Id: I4bb8985c43f54dadf85a92c96cc81a402cfaa4a5
Change-Id: Id88c37afff06bd760c174d1a7aaa84ca724c94ad

PLDM support power caps based on power supply number,type,input voltage

---

common/utils.cpp
host-bmc/dbus_to_host_effecters.cpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
softoff/main.cpp

Handling the exception thrown by new_method_call

Handle Dbus query exception gracefully

---

libpldmresponder/base.cpp
oem/ibm/configurations/bios/enum_attrs.json
oem/ibm/configurations/bios/integer_attrs.json

change PLDM to get a more accurate Present on power supplies. name of attribute will change in the future.

Attr 1050 v6

---

oem/ibm/configurations/events/oem_ibm_event_state_sensor.json

This commit adds the JSON changes necessary to
support IPV6 configurations.

JSON changes for IPV6 support.

---

oem/ibm/libpldmresponder/inband_code_update.cpp

As per current design of PLDM, newly forked process assembles lid files and create a tar ball of code update image. But any error occured during assembling process was not communicated to host by the forked process.
Now on Phosphor-bmc-code-mgmt repo will take care of assembling the lid files.
PLDM calls the DBus method AssembleLids hosted by bmc-code-mgmt after receiving end update from host.
And keeps listening to the Version path and Activation interface. Based on Activation value(Active/Invalid) takes necessary action.
Tested:
Inband Code update (success/failure) tested successfully.

Trigger Assemble-lids method and handle response

---

oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/file_io_by_type.cpp
oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/file_io_type_pel.cpp

This commit adds changes to enhance or give context to the generic error traces related to file offset errors.

Enhance traces for File offset issues

---

oem/ibm/libpldmresponder/file_io_type_lid.hpp

This commit adds change to send the right error code to host during the marker lid validation. When the marker lid validation fails we were trying to send a PLDM_ERROR But it was sent as a response to the file write request and PHYP assumed that the error code returned was for the write operation and did not go ahead to check the sensor event sent to indicate the entitlment fail during marker lid validation.
Defect: PE00LNC2

Return proper Success/Error code to host

---

oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json

This commit adds the missing bracket in the JSON entry. 
Fixes: 569181
Change-Id: If57646ee6243a5c9c69b7ef746abfd2ae8e198b9

pdr: Missing "{" in JSON entry

---

oem/ibm/pfw-sms-utils/pfw_sms_menu.cpp

Fixed bug in PFW SMS Menu password handling
Tested: tested successful and failed auth

Fixed bug in password handling

---

oem/ibm/libpldmresponder/oem_ibm_handler.cpp

This commit enhances the error logs for journal in the set host effecter states flow.

oem-ibm: Enhancing FFDC journal for setHostEffecterState

---

.secrets.baseline
oem/ibm/libpldmresponder/file_io.cpp
oem/ibm/libpldmresponder/file_io.hpp
oem/ibm/libpldmresponder/file_io_by_type.hpp
oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/libpldmresponder/file_io_type_dump.hpp
oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/file_io_type_pel.hpp
oem/ibm/libpldmresponder/file_io_type_progress_src.hpp

This contains the necessary 1110 dump changed split into different commits.
Tested fine with dump team.
tests involved - 
Initiating resource dumps, system dumps.

pldm: Dump support in 1110

---

host-bmc/host_pdr_handler.cpp
host-bmc/host_pdr_handler.hpp
libpldmresponder/platform.cpp

The commit brings in necessary changes for PDR exchange in 1110 branch.

pdr: PDR changes support in 1110

---

common/test/mocked_utils.hpp
common/types.hpp
common/utils.cpp
common/utils.hpp
host-bmc/dbus_to_event_handler.hpp
libpldmresponder/fru.cpp
libpldmresponder/fru.hpp
libpldmresponder/meson.build
libpldmresponder/oem_handler.hpp
libpldmresponder/pdr_numeric_effecter.hpp
libpldmresponder/pdr_state_effecter.hpp
libpldmresponder/pdr_state_sensor.hpp
libpldmresponder/pdr_utils.hpp
libpldmresponder/platform.cpp
libpldmresponder/platform.hpp
libpldmresponder/test/libpldmresponder_fru_test.cpp
oem/ibm/libpldmresponder/collect_slot_vpd.cpp
oem/ibm/libpldmresponder/collect_slot_vpd.hpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp
oem/ibm/libpldmresponder/utils.cpp
oem/ibm/libpldmresponder/utils.hpp
oem/ibm/test/libpldmresponder_oem_platform_test.cpp
pldmd/pldmd.cpp

concurrent maintenance and hotplug functionalities are added. with this change. It has been verified by modifying and adding and removing PDRs from BMC
Tested By:
setting the fan0 presence property is set to false first (as it is by default true after PDRs are built on BMC). then it is set to true so that individual FRU/PDR is built.
getPDR o/p -
all 4 types of PDR added at the end with instance number 7.
,{
"nextRecordHandle": 417,
"responseCount": 20,
"recordHandle": 416,
"PDRType": "FRU Record Set PDR",
"dataLength": 10,
"FRURecordSetIdentifier": 68,
"entityType": "[Physical] Fan",
"entityInstanceNumber": 7,
"containerID": 3
}
,{
"nextRecordHandle": 418,
"responseCount": 27,
"recordHandle": 417, …

Concurrent maintenance and hotplug

---

oem/ibm/libpldmresponder/file_io_type_dump.cpp
oem/ibm/requester/dbus_to_file_handler.cpp
oem/ibm/requester/dbus_to_file_handler.hpp

This commit adds some new PELs [1].
[1]: https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/73483

PEL: Adding a few PELs

---

common/utils.cpp
common/utils.hpp
host-bmc/host_pdr_handler.cpp
libpldmresponder/bios_config.cpp
libpldmresponder/oem_handler.hpp
libpldmresponder/platform.cpp
oem/ibm/libpldmresponder/file_io_type_lid.hpp
oem/ibm/libpldmresponder/inband_code_update.cpp
oem/ibm/libpldmresponder/inband_code_update.hpp
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
oem/ibm/libpldmresponder/oem_ibm_handler.hpp
oem/ibm/test/libpldmresponder_oem_platform_test.cpp
softoff/softoff.cpp

This PR contains the following commits:
Concurrent code update support.
Bootside mapping
Support for boot types attributes
All the defect fixes for inband and out of band updates in pldm.
surveillance timer. 
TESTED: Tested by doing inband updates and out of band updates.

1110 codeupdate- inband and Concurrent update rebase

---

oem/ibm/configurations/fileTable.json

Add new hostboot hash lids 80d0004* and hostboot tool data lid 81e006f0.
Change-Id: Id0578f4cce8a5248b2cd1e41da520690cd9f1183

oem: ibm: fileTable: Add hostboot hash lids

---

oem/ibm/libpldmresponder/utils.cpp

Adding a presence check of the fru before populating the topology information.
Now with the new changes in inventory single PCIeSlot can contain either Disk Backplane or Cable card, to support both of them inventory is population all the connectors underneath disk backplane as well cable card and "Present" property provides the information about which connectors are active.
Added the check of "Present" property before populating the topology info for that perticular location code.

oem: Check fru presence before updating topology information

---

oem/ibm/libpldmresponder/utils.cpp

Adding a presence check of the fru before populating the topology information.
If the JBOF card is replaced by cable card in the slot, the Dbus inventory under the PCIe card contain all the connectors underneath JBOF card as well as cable card and "Present" property provides the information about which connectors are active at the moment. PLDM need to check "Present" property to fetch the right object path to create the proper association.

oem: Check presence of the fru for topology information

---

requester/handler.hpp
requester/test/handler_test.cpp

This reverts commit 3f30301236076e1806640c8b127198321bdaebad.

Revert "requestHandler: Queue the request messages to one endpoint (#…483)"

---

.clang-format
libpldmresponder/test/libpldmresponder_bios_test.cpp
oem/ibm/configurations/fileTable.json
oem/ibm/libpldmresponder/utils.cpp

Change-Id: Ice0d0734e7adf27c3d96fb345f6615d45842594b

oem: ibm: fileTable: Add lids for Balcones system

---

oem/ibm/libpldmresponder/file_io_type_pel.cpp

```
The storePel function used call_noreply, a synchronous D-Bus method
with timeout of 5 secs, which caused it to timeout in some scenarios.
To mitigate this issue, it has been replaced with call_async method.
Additionally, PLDM_SUCCESS is being returned now regardless of
the method call outcome. In case of any error during the async
method call, it will be logged by the callback function.
Change-Id: Ifbb80585ace516c8d4bf484c08356c3734d351fc
Signed-off-by: Jino Abraham <jinoabraham26@gmail.com>```

1060: libpldmresponder: Use async call in storePel (#675)
