host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
This commit changes the first command to async that pldmd sends
after starting to discover Host state.
Also uses GetPLDMVersion as the first command so that Host understands
bmc pldmd has restarted.
Change-Id: Icb556a89f3cc9564450cc344ba9e0e8b56421fd9
Signed-off-by: Sampa Misra <sampmisr@in.ibm.com>
=> pldmd: use async instead of event loop at start

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
The Host watchdog timer is started when the BMC is
powered on with a predefined timer interval. BMC
monitors if the Host boots without failures and
Host is supposed to ping the BMC(through
PlatformEventMessages) within the watchdog timer
interval expiration and BMC resets the watchdog
timer on receiving pings from Host and in case
the Host fails to ping the BMC within the timer
interval expiration, then BMC will trigger a host
dump.
This commit is to disable the watchdog timer after
host poweron completion, which will be followed by
surveillance(monitoring of BMC by Host).
Change-Id: I734e6e98f6c2936aebd04c0b56bdfebba4cfd40b
Conflicts:
oem/ibm/libpldmresponder/oem_ibm_handler.cpp
=> Fix for "Failed To disable watchdog timerERROR=std::get: wrong index for variant"

oem/ibm/configurations/bios/enum_attrs.json
This commit adds 5 new bios attributes as mentioned below
- pvm_os_boot_type_current
- pvm_rpa_boot_mode_current
- pvm_default_os_type_current
- pvm_stop_at_standby_current
- pvm_vtpm_current
TESTED: BMC power on successful with the enum_attrs.json
Change-Id: I3fb42e328d6417188f166bf9ae5382209e38feab
=> BIOS: Add 5 new bios attributes in enum_attrs.json

host-bmc/custom_dbus.cpp, host-bmc/custom_dbus.hpp
- Upstream Gerrit [link](https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/46229) for the same patch
=> host-bmc: Implemented Enable interface for Core objects

common/types.hpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/pdr_utils.cpp, libpldmresponder/platform.cpp
This bug was actually caused by two host sensors that has the
exact same entity id, instance id, container id but being used
to implement different state sets.
The old host code had two sensors on processor module that implements
both stateset 1 & 11 that caused this regression and using this PR we
have improved the sensor parsing abilities so that we can compare the
state setId as well before deciding that a sensor is unique.
=> Fix the looping behaviour in the getstatesensorreading command

pldmd/pldmd.cpp
- 20aa3e09fb866c1b99c1d3d702f2a2f1908558af commit moved the
setHostFirmwarecondition() function call prior to the code
that connects to the mctp socket.
- That led us to fail in sending the message with ENOTCONN Errno,
as demonstrated by the below strace log.
```
------
23:16:50.596833 connect(3, {sa_family=AF_UNIX, sun_path=@"mctp-mux"}, 11) = 0
Change-Id: Icd3a20e4bb0218517d44d14a57c0407c7b7702e2
---
23:16:50.593800 sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\t\1",
iov_len=2}, {iov_base="\200\0\3\0\0\0\0\1\0", iov_len=9}], msg_iovlen=2, msg_controllen=0,
msg_flags=0}, 0) = -1 ENOTCONN
-----
```
- Without this change , we would get ENOTCONN(107 errono) for the
getPLDMVersion command that pldm sends at the beginning to discover the
host state.
tested by:
1. when the …
=> Fix for discovering the HostState

libpldmresponder/platform.cpp
This commit fixes the unsupported eventDataOperation
in the pldmRepoChangeEvent handler. This unsupported
operation was causing a interleaved recordHandles of
PDRs from the host.
Tested: Using pldmtool, no looping of PDRs was observed.
Change-Id: I94fbab0107deefe5d6d2accdc640cf3f86aee8ad
=> PLDM : Temporary fix in the pldmRepoChangeEvent

oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/requester/dbus_to_file_handler.cpp
This commit include following changes:
1. Allow the empty string as resource dump selector
2. Avoid setting the resource dump dump explicitly as notify method
takes care of the same. This code was causing error when the
resource dump is getting initiated from host
Tested and verified that resource dump initiation from host is
getting completed without any error.
Change-Id: I58f51cb115d86ae22099d57474a1159d8952cefa
=> oem-ibm: Resource dump related fixes

host-bmc/host_pdr_handler.cpp
This commit fixes the hang issue caused when
booting to host runtime followed by restarting pldmd
followed by power off and power on.
The variable responseReceived is set to false when the
host powersOff.
Change-Id: I47d6570fffec7b5c86db102f891f7a96f66f1f39
=> fix for a poweron hang

oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/inband_code_update.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
The assembling of the tarball image file is a long running process,
causing pldm to not reply to any other requests until it's done, causing
errors such as when the hypervisor tries to ping the bmc to determine if
it's running.
Move the assembling of the image to a forked process so that it runs in
the background. Move the assembling function to the code update class so
that it has access to the code update sensor to set it to error if an
failure occurs, since no parent process will wait for it.
Use double fork to avoid zombie tasks, this allows the grandchild to be
reparented to init.
Tested: Verified the hypervisor did not reset the BMC during an inband
update because it didn't receive a reply to its ping request.
Change-Id: I47d5fde1a1311e94d5b03f7fcf4c0ab15ba054e3
Signed-off-by: …
=> oem: ibm: Assemble the image in a forked process

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json
hb_power_limit_enable and hb_power_limit_in_watts were previously
defined as latched/pending attributes. This is being changed because
when these values are changed, the new value is immediately sent to
the OCCs, and firmware needs to process the latest value that the OCC
received rather than the one effective at the beginning of the IPL.
Change-Id: Ida39a3ee5e6b4b0d3255bfef95601890afd80709
Signed-off-by: Zach Clark <zach@ibm.com>
=> Remove hb_power_limit_enable_current and hb_power_limit_in_watts_current

oem/ibm/configurations/bios/enum_attrs.json
This commit defines the hb_inhibit_bmc_reset BIOS attribute. When set
to the enumeration value "Inhibit", Hostboot will instruct PHYP via
HDAT to not reset/reload the BMC at runtime.
Signed-off-by: Zach Clark <zach@ibm.com>
Change-Id: Ibb5ec25649c1c0c5532ae0c93003f46213fe32b1
=> Define the hb_inhibit_bmc_reset BIOS attribute

oem/ibm/requester/dbus_to_file_handler.cpp
An unwanted system dump is being generated if the resource dump is
initiated from hypervisor with an empty vsp string. So the fix here
is to additionally check the resource dump progress status and block
sending the command to hyperviosr if the status is not in progress.
Tested by initiating a resource dump from hypervisor and extra system
dump is not observed anymore.
Change-Id: I25c1db3510d6f44b354881e4065aa148fe618464
=> oem: Fix to remove extra system dump

oem/ibm/configurations/bios/string_attrs.json
Merged upstream: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/48788
More lid ids are being added to map runtime lids to human readable
names so we must increment the max size to account for this.
Signed-off-by: Christian Geddes <crgeddes@us.ibm.com>
Change-Id: I3a6037ecef37b4d2768d528267018cacfaf1a58a
=> Increment max size of hb_lid_ids from 512->1024

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
This commit sets the slot power state to off when the
host powers off. The host only powers on the slots and
the BMC needs to turn all the slots off when the host powers off.
Tested using the busctl commands.
Change-Id: Ie1fe384638a756f2657ea113e8f8aa5e9caace2b
=> PLDM: Setting the slot power state to Off

softoff/softoff.cpp
This commit updates the pldm-softpoweroff application so that it can
properly locate the PLDM effecter and sensor PDRs for the graceful
poweroff request. It also updates the host terminus ID to the correct
value.
Tested by:
Running the application when Hostboot was IPLing, and also when PHYP
was at standby.
root@ever39bmc:~# /tmp/pldm-softpoweroff
Getting the response. PLDM RC = 0
Timer started waiting for host soft off, TIMEOUT_IN_SEC = 0x1c20
root@ever39bmc:~# echo $?
0
Signed-off-by: Zach Clark <zach@ibm.com>
Change-Id: I7408611881abecfb5169816af032e2fb9d3a8a09
=> Update pldm-softpoweroff application with working values

host-bmc/host_pdr_handler.cpp, libpldmresponder/event_parser.cpp, libpldmresponder/event_parser.hpp, libpldmresponder/platform.cpp, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/configurations/events/oem_ibm_event_state_sensor.json
Phyp currently creates the container ID's dynamically, so
we will not able to know the Id of the containers beforehand.
So this PR would be adding support to skip checking for entities
that does not have container Id's mentioned in the events json.
Fixes : SW540578 & SW540536
Tested By :
On Rainier :
type : 57346
instance : 0
conId : 32779
name : Enabled
interfacexyz.openbmc_project.Object.Enable
obj path : /xyz/openbmc_project/network/hypervisor/eth0/ipv4/addr0
entered the try block
value : 0 ,service :xyz.openbmc_project.Network.Hypervisor , interface : xyz.openbmc_project.Object.Enable , path : /xyz/openbmc_project/network/hypervisor/eth0/ipv4/addr0
type : 57346
instance : 0
conId : 32779
name : Enabled
interfacexyz.openbmc_project.Object.Enable
obj path : …
=> Add support to skip container ID checks in events

configurations/pdr/4.json, libpldmresponder/pdr_numeric_effecter.hpp, libpldmresponder/pdr_state_effecter.hpp, libpldmresponder/pdr_state_sensor.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp, libpldmresponder/test/libpldmresponder_pdr_effecter_test.cpp, libpldmresponder/test/libpldmresponder_pdr_sensor_test.cpp, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp, pldmd/pldmd.cpp
It is not always a standard condition that we should have
a fru record set PDR, we can also have sensors/effecters
without having an associated FRU record set PDR.
This commit would help add these orphan sensors/effecters
entities into the entity association PDR's.
Fixes : SW536590 & SW536589
=> Add orphan entities to the Entity Association PDR's

host-bmc/custom_dbus.cpp, host-bmc/custom_dbus.hpp, host-bmc/dbus_to_event_handler.cpp, host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, host-bmc/test/custom_dbus_test.cpp, libpldmresponder/meson.build, libpldmresponder/test/meson.build, oem/ibm/host-bmc/host_lamp_test.cpp, oem/ibm/host-bmc/host_lamp_test.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/test/host_bmc_lamp_test.cpp, pldmd/pldmd.cpp
This PR would add
1.Lamp test support from pldm
2. Mex critical associations for health rollup function.
3.Also removes some unwanted trace
=> Lamptest & Mex critical associations support

oem/ibm/libpldmresponder/fru_oem_ibm.cpp
This commit sets the PCIE config space data sent from
host with a prefix '0x' and the hex value. This change
was needed as the Redfish validator expects the fields
to be in a particular Regex form otherwise it fails to
validate.
Tested:
By using busctl commands to set the fields with the data
sent and also ran the Redfish validator to verify.
=> PLDM: Hex value support for the PCIE config space data

configurations/pdr/4.json
Add a new composite state sensor to the state sensors JSON file.  The
composite sensor describes the state of an Uninterruptible Power Supply
(UPS) attached to the system.
The composite sensor is contained in the "Logical System" with container
ID 1.  The sensor provides the following state sets:
* 259 - Backup Power Source
* 261 - Battery Activity
* 262 - Battery State
This sensor is not system-specific, so it was added to the common
(non-OEM) state sensors JSON file.
Testing:
* Copied the modified 4.json file to the /usr/share/pldm/pdr directory
on the BMC and re-started the pldmd.service.
* Ran 'pldmtool platform GetPDR -t stateSensor' and verified the new
composite sensor exists in the output with the correct field values.
* Ran 'pldmtool platform GetStateSensorReadings' for the new …
=> Add composite UPS state sensor to JSON file

oem/ibm/libpldmresponder/fru_oem_ibm.cpp
There is a bug in a code, where we ignore the PCIe Config
information that is sent by the PHYP for IBM Cable cards.
This PR would fix the issue.
=> Fix: Set PCIeConfig Information for IBM Cards

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
DVT team opened a release blocking defect because system is
intermittently auto powering on when it should not.
Need to get to root cause on why this new code is setting the
RestorePolicy to AlwaysOn occasionally. Until this is figured out,
disable the function.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
=> power-restore-policy: disable setting temporarily

oem/ibm/configurations/pdr/ibm,everest/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-2u/11.json, oem/ibm/configurations/pdr/ibm,rainier-4u/11.json
The slot power state effecters where missed when we moved
to platform specific PDRs. This commit adds them back.
=> PLDM:add back the slot power state effecters

oem/ibm/libpldm/file_io.h, oem/ibm/libpldmresponder/file_io_type_dump.cpp
This commit includes following changes:
1. Support to delete the resource dump entry when dump after dump
was being offloaded to OS in non-hmc managed systems
2. Changed the bus call method for not to use noreply option
Change-Id: I7526cfee89361f7d51ea709c9a7162c8985ab394
=> oen-ibm: Resource dump entry delete support

configurations/events/stateSensorPdrs.json, host-bmc/host_pdr_handler.cpp, libpldmresponder/event_parser.cpp, libpldmresponder/event_parser.hpp, libpldmresponder/platform.cpp, libpldmresponder/test/event_jsons/good/event_state_sensor.json, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/configurations/events/oem_ibm_event_state_sensor.json
In the current state pldm does not support having state setid
field in the event jsons, this PR would add that support in PLDM
there by allowing hosts to have multiple sensors with the same
entity instance number, type & container id but with different
state sets.
Fix for : SW542285
=> Add stateset id support for remote sensor events

oem/ibm/configurations/bios/integer_attrs.json
vmi_if_count is a deprecated attribute and is not used by
phyp, so removing it from pldm json files.
Fixes : SW542127
=> bios: Remove deprecated vmi_if_count bios attribute

host-bmc/custom_dbus.cpp, host-bmc/custom_dbus.hpp, host-bmc/host_pdr_handler.cpp
PHYP sends a FRU record set PDR and send the io enclosure
version data via the frurecord table, and pldm parses that
and hosts the Version Interface on the mex chassis object.
Currently phyp does not have the support for this yet, so
hardcoded a dummy value for now, would have to remove that part
of code once the phyp change is in the driver.
=> Support for Mex IO Enclosure version

oem/ibm/requester/dbus_to_file_handler.cpp
This is to remove the extra bytes in the new file available request
to hypervisor when the ACF file is fetched from the system while
initiating a resource dump.
Change-Id: Iff2143f6f76a1a1ae588891a4a14159288b3df06
=> oem-ibm: Remove extra bytes in resource dump request

oem/ibm/configurations/bios/enum_attrs.json
IBM legacy behaviour is to boot to runtime by default, so changing
this attribute default value to align with the legacy designs.
Fixes : SW542764
Change-Id: I26873e3574dc37554b090fce32f047e5aebe0a6f
=> oem_ibm: bios : change the default value of pvm_stop_at_standby

oem/ibm/libpldmresponder/inband_code_update.cpp
Add support for pvm_fw_boot_side attribute till HB starts using
fw_boot_side_current attribute
=> PLDM: Add support for pvm_fw_boot_side

host-bmc/host_pdr_handler.cpp, host-bmc/utils.cpp, libpldm/pdr.c
- The map seems to be good in the genesis boot
- But is getting corrupted due to deletion on the
remote PDR's when host is off.
Fixes : SW542079 & SW542324
=> Fix object map corruption in pldm

host-bmc/host_pdr_handler.cpp
There is a bug in pldm where we reduce the fru record table
twice , This is leading to the last few bytes being chopped
off at the end of the fru record table.
Fixes SW542325
=> Fix the fru record table size

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
When the host is off, the dbus objects for cores and mex
would be just a dummy and a user would be not able to do any
operation on those.
So, PLDM would host the Availability interface on all the
dbus object and set the availability to false when the host
is off, and set them back to true right after the PDR exchange.
There should be a corresponding change required in redfish
to look for the availability state and mark the redfish state
as Unavailable offline.
Fixes : SW542400 & partially fixes SW542325
=> Host availability interface on cores & mex dbus objects

host-bmc/host_pdr_handler.cpp
There was a bug in PLDM were post reboot when the host is up
we talk to HBRT to get sensor states of OCC and cores etc.
and when we power off that is not reverted back to the valid eid.
This was not triggered till now as we were getting bad TL PDR for
HBRT.
=> PLDM: fix for SW543085

host-bmc/host_pdr_handler.cpp, libpldmresponder/fru.cpp
This fixes the Duplicate PLDM Record Handles sent
to the host on IOCM Fan Add.
This also removes a trace line in the code.
=> PLDM: fixes SW542086 and removes a trace line

oem/ibm/libpldmresponder/inband_code_update.cpp
Include additional debug traces for the bootside in
the case where we end up in the previously observed
error path(SW542685)
=> PLDM: Include additional debug traces

oem/ibm/configurations/bios/enum_attrs.json
This commit adds the pvm_keep_and_clear BIOS attribute.
This is needed as PHYP needs to clear most of PHYP NVRAM,
but preserve the NVRAM for the manufacturing default partition.
=> oem_ibm: Define the pvm_keep_and_clear BIOS attribute

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
As PHYP team had corrected the HBRT Terminus locator PDR,
now bmc can query both phyp and HBRT both at a time in parallel
to fetch the status of the sensors owned by phyp and also by HB.
=> Fetch Hostboot sensor status from HBRT

oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, pldmtool/oem/ibm/oem_ibm_state_set.hpp
Real SAI effecter
================
{
"nextRecordHandle": 138,
"responseCount": 30,
"recordHandle": 137,
"PDRType": "State Effecter PDR",
"dataLength": 16,
"effecterID": 24,
"entityType": "[Physical] OEM IBM Real SAI(OEM)",
"entityInstanceNumber": 1,
"containerID": 1,
"effecterSemanticID": 0,
"effecterInit": "noInit",
"effecterDescriptionPDR": false,
"compositeEffecterCount": 1,
"stateSetID[0]": "Operational Fault Status(10)",
"possibleStatesSize[0]": 1,
"possibleStates[0]": [
"Normal(1)"
]
}
Real SAI sensor
===============
{
"nextRecordHandle": 139,
"responseCount": 28,
"recordHandle": 138,
"PDRType": "State Sensor PDR",
"recordChangeNumber": …
=> OEM-IBM: PDR: Add Real SAI sensor and effecter Support

common/flight_recorder.hpp, common/utils.cpp, common/utils.hpp, meson.build, meson_options.txt, pldmd/pldmd.cpp, requester/request.hpp, softoff/main.cpp, softoff/meson.build, softoff/services/pldmSoftPowerOff.service, softoff/softoff, softoff/softoff.cpp, softoff/softoff.hpp
This PR consists of 2 changes :
1. flight recorder upstream changes 
2. --notimeout option for the pldmsoftoff app
softoff testing :
without timeouts:
==============
root@rain118bmc:~# ./pldm-softpoweroff --notimeout
Not applying any time outs
Tx: 80 02 39 03 00 01 01 06
Got the response for set effecter states command, PLDM RC = 0
Rx: 00 02 39 00
Recieved the graceful shutdown signal from host
With timeouts:
=============
root@rain118bmc:~#obmcutil poweroff
Feb 17 14:43:35 rain118bmc systemd[1]: Starting PLDM soft power off app...
Feb 17 14:43:35 rain118bmc pldm-softpoweroff[4056]: Tx: 80 02 39 03 00 01 01 05
Feb 17 14:43:35 rain118bmc pldm-softpoweroff[4056]: Got the response for set effecter states command, PLDM RC = 0
Feb 17 14:43:35 rain118bmc pldm-softpoweroff[4056]: Timer started …
=> Add notimeout option for pldmsoftoff

libpldm/meson.build, libpldm/pdr.c, libpldm/pdr.h, libpldm/tests/libpldm_pdr_test.cpp, libpldmresponder/fru.cpp, libpldmresponder/fru.hpp, oem/ibm/libpldm/pdr_oem_ibm.c, oem/ibm/libpldm/pdr_oem_ibm.h, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/utils.cpp
This commit fixes the fru table issue and also the record handles.
The record handles of the PDRs were messed up during the
normal poweron and a CM operation.
Tested on both rainier and everest systems and boots fine.
=> PLDM fru and record handle fix

oem/ibm/configurations/pdr/ibm,everest/11.json, oem/ibm/configurations/pdr/ibm,everest/4.json
effecter lcd panel identify
=========================
{
"nextRecordHandle": 260,
"responseCount": 29,
"recordHandle": 259,
"PDRType": "State Effecter PDR",
"dataLength": 19,
"effecterID": 142,
"entityType": "[Physical] Chassis front panel board(control panel)",
"entityInstanceNumber": 2,
"containerID": 5,
"effecterSemanticID": 0,
"effecterInit": "noInit",
"effecterDescriptionPDR": false,
"compositeEffecterCount": 1,
"stateSetID[0]": "Identify State(17)",
"possibleStatesSize[0]": 1,
"possibleStates[0]": [
"Identify State Unasserted(1)",
"Identify State Asserted(2)"
]
}
pldmtool platform SetStateEffecterStates -i 142 -c 1 -d 1 1
{
"Response": "SUCCESS"
}
busctl …
=> PDR: Add LCD panel and connector support for everest

oem/ibm/libpldmresponder/file_io_type_dump.cpp
This commit is to fix the dump offload issue by using
GetManagedObjects instead of GetSubTreePaths to search for the
dump entry match. This also adds the support the delete of
non-disruptive system dump entry in non-hmc managed scenario
after a successful offload of the dump to OS.
Tested by triggering a non-disruptive system dump using an empty
vsp string. Also tested the system dump and resource dump offloads.
CQ: SW544034
Change-Id: Ia46c2f3b654d509c6669e909ff803958f5a8f4ea
=> oem_ibm: Fix for dump offload and system dump delete issues

oem/ibm/libpldmresponder/oem_ibm_handler.hpp
Changing PLDM_OEM_IBM_ENTITY_REAL_SAI ID from 24578 to 24581 as per discussion in mail chain
@jaypadath @sampmisr
=> OEM-IBM: Change PLDM_OEM_IBM_ENTITY_REAL_SAI ID

configurations/pdr/11.json
The termination status effecter when set to Graceful restart
state should request the state manager to start the GracefulWarmReboot
NOT the ForceWarmReboot.
ForeWarmReboot target would not trigger the pldm-softoff application,
so it forcefully shuts down the host rather than waiting for it to
acknowledge.
Change-Id: I769dfc57a34e0938f3ca317db0eca8d6b85e7566
=> Fix support for Graceful restart effecter

libpldmresponder/platform.cpp
In the current flow, if the entity type is in the OEM range,
then in both the getStateSensorReadings & setStateEffecter handler
flow, we would trigger the oem functions rather than the generic
functions (which handles the PDR's in json format) - while this gives
a seperated infrastructure, this would also limit us from using the
json infrastructure for OEM entities.
This fix would basically allow defining the OEM entities in the standard
PDR json files, and also allow us to seperate out a new 11.json & 4.json
into the oem/<vendor> configuration folders.
Tested By :
Running macro: iocmnm -dumppdrindicatorstates
Ident             Fault         |=Pdr Entity=|
repo  SensorId  ident  SensorId  fault Type Inst Cont Location code
==== ========== ===== ========== ===== ==== ==== ==== …
=> Allow OEM Effecters & Sensors to take json path

libpldmresponder/bios_config.cpp
This is change to provide support for the
next boot side(fw_boot_side) set by host
=> PLDM: Next Boot Support

oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
The nextBootSide and currBootSide should have a value of "T" or "P", but
the side bios attributes have values of "Temp" or "Perm". There were a
couple places where the value of the attributes were being assigned to
the boot side variables without making the translation. Fixed by
converting "Temp/Perm" into "T/P".
Tested: Verified pldm returned the correct lid data from the requested
side after a code update.
Change-Id: I95f4087bfe382cf468a294fb18fdc8309b5b0bbc
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
=> oem: ibm: Fix BootSide string values

oem/ibm/libpldmresponder/file_io_type_lid.hpp
To add support for the new filetype PLDM_FILE_TYPE_LID_RUNNING
in constructLidpath for host to request the running side lids.
Defect: SW544140
=> PLDM: Support for LID type running in constructLidpath

libpldmresponder/pdr_numeric_effecter.hpp, libpldmresponder/pdr_state_effecter.hpp, libpldmresponder/pdr_state_sensor.hpp
The LED effecter and sensor PDRs where created even when
the FRU or the entity path was not present which puts the
entity ID in the PDR as 0. This commit fixes that issue.
Fixes:SW537409
=> fix the invalid effecter and sensor PDRs

libpldm/state_set.h, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, pldmtool/oem/ibm/oem_ibm_state_set.hpp, pldmtool/pldm_platform_cmd.cpp
This commit adds a single OEM state effecter with a 
OEM entity type and with states [7,9,10] to perform 3 custom
actions ReIPL, PowerDown and ArmAPR.
fixes:SW531941
=> PLDM Power down effecter and APR support

libpldm/state_set.h, oem/ibm/configurations/pdr/ibm,everest/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-2u/11.json, oem/ibm/configurations/pdr/ibm,rainier-4u/11.json, pldmtool/pldm_platform_cmd.cpp
Add Power state PDR for rainier 1S-4U, rainier 2U, rainier 4U and everest platforms
Sample PDR info captured from everest
{
"nextRecordHandle": 698,
"responseCount": 29,
"recordHandle": 697,
"PDRType": "State Effecter PDR",
"dataLength": 19,
"effecterID": 357,
"entityType": "[Physical] Slot",
"entityInstanceNumber": 9,
"containerID": 5,
"effecterSemanticID": 0,
"effecterInit": "noInit",
"effecterDescriptionPDR": false,
"compositeEffecterCount": 1,
"stateSetID[0]": "Device Power State(257)",
"possibleStatesSize[0]": 1,
"possibleStates[0]": [
"Unknown(0)",
"Fully-On(1)",
"Off(4)"
]
}
=> oem-ibm: Add power state PDRs for P10 platform.

oem/ibm/libpldmresponder/file_io_type_dump.cpp
This commit fixes the upstream component
which is passed to read the dump file which
suggests if the dump is offloaded to host or
not, in case of Dump Offload in non-HMC managed
scenario
=> PLDM: Fix for upstream component

oem/ibm/configurations/events/oem_ibm_event_state_sensor.json
When there is a OS IPL mode sensor state change event from PHYP,
the event state value needs to be updated in OSIPLMode dbus property
hosted by com.ibm.PanelApp service.
This commit updates oem state sensor json with the OS IPL Mode sensor
info with the corresponding panel dbus property that needs to get updated.
Test:
Tested on rainier.
case 1: Set OS IPL mode sensor state as ENABLED
root@p10bmc:/tmp# busctl get-property com.ibm.PanelApp /com/ibm/panel_app com.ibm.panel  OSIPLMode
b false
root@p10bmc:/tmp#
root@p10bmc:/tmp# pldmtool raw --data 0x80 0x02 0x0A 0x01 0xD0 0x00 0x05 0x00 0x01 0x00 0x01 0x02
pldmtool: Tx: 08 01 80 02 0a 01 d0 00 05 00 01 00 01 02
pldmtool: Rx: 08 01 00 02 0a 00 00
root@p10bmc:/tmp#
root@p10bmc:/tmp# busctl get-property com.ibm.PanelApp /com/ibm/panel_app …
=> Update dbus-property for OS IPL mode state sensor change

oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp
This is needed for dump manager to identify if a dump offload
in progress so that it can reject other host dump requests.
Tested by:
Offloading system dump and resource dump
=> DumpHandler: Reset dump OffloadUri after dump offload

libpldmresponder/platform.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This PR would fix mutiple issues :
1.When ever pldm is started , it sends a getPLDMVersion
command to host and if we get a response we set HostUp
to true. But we started to see cases where PHYP does not
respond to getPLDMVersion but instead does a GetPDR command.
So we have a minimal window where we could go ahead and create
PDR's even when BMC is not in Ready State.
2.Check for other BMC states and don't allow anyone to create PDR's
if BMC is not in Ready state.
=> Fix Race condition in PDR generation

libpldmresponder/bios_config.cpp, oem/ibm/libpldmresponder/inband_code_update.cpp
This commit removes the old boot side setting of
bios attribute pvm_fw_boot_side which is now
deprecated.
Also adds an additional check before setting the
fw_boot_side bios attribute before setting the new
value which is set by host to make sure that the
bios attibute table is initiated before we try to
set the value.
=> PLDM: Remove old boot side setting

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, libpldmresponder/platform.cpp
This commit fixes the incorrect handling of multiple
PDR records modified events sent by the host which are
all sent within fraction of seconds.
Defect: SW546471
=> PLDM: Fix for OpPanel enable function 34

host-bmc/dbus_to_host_effecters.cpp, oem/ibm/libpldmresponder/platform_oem_ibm.cpp
SystemSetup is a BootProgress that indicates the host is booted, but in
a state where user interaction is needed. On an IBM system, this state
is entered when VMI needs some configuration or when PHYP's NVRAM has
been cleared.
pldm needs to consider the host running in this scenario because it's
needed to send user configuration information like the VMI IP and
static vs. dhcp information.
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
=> support a BootProgress of SystemSetup for host running

oem/ibm/configurations/bios/enum_attrs.json
Upstream Commit: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/52268
External IBM clients to the BMC need to known when a memory preserving
reboot is occurring. A power off of the system during this process will
result in all the debug data that is collected during this process be
lost. This new BIOS value will be set when a memory preserving reboot is
started, and cleared when the debug data has been offloaded by the
client. Redfish clients can look at this BIOS value to know if they
should allow a power off of the system.
The initial goal was to work this into the official system states
reported by the BMC (redfish/v1/Systems/system) but Redfish really
doesn't have this type of function well represented currently. A memory
preserving reboot is pretty specific to IBM systems. …
=> oem-ibm: define new pvm_sys_dump_active bios value

oem/ibm/libpldmresponder/inband_code_update.cpp
This commits add code to minimise sending redundant bios
attribute change events to host.
Defect:SW546927
=> PLDM: Minimise sending BIOS attr change event

host-bmc/host_pdr_handler.cpp, libpldmresponder/pdr_utils.cpp, libpldmresponder/platform.cpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp
1. Adding trace when we get the repo change event which indicates
did PLDM exchange between BMC and host happen (i.e. did BMC see
the "PDRs changed" event come in from host, and read out the PDRS).
2. Adding trace when we send repo change event back after
merging the PDRs which indicates did host come down and read
all the PDRs after BMC told it that the PDR repo changed.
3. printing the first and last record handle in bmc repo after each
PDR exchange.
4. Adding trace when we get a TerminusLocator PDR from host.
Solution for #SW548456
=> FFDC enhancement

host-bmc/host_pdr_handler.cpp
Previously we had just put a dummy string in version property
to unblock other teams, now that phyp is already supporting it
we have removed that hardcoded string and setting it with real
data that is coming from phyp.
Tested by:
1. power on to phyp standby
2. check the mex chassis dbus object
xyz.openbmc_project.Software.Version                 interface -         -                                        -
.Purpose                                             property  s         "xyz.openbmc_project.Software.Version.V… emits-change writable
.Version                                             property  s         "03MEX200924a"                           emits-change writable
3. check the mex version using phyp macro and make sure both match
Rack    Unit  Location           Status …
=> mex : Set the real mex firmware version from phyp

oem/ibm/libpldmresponder/file_io.cpp
These changes will handle the case where host crashes in the
middle of outofband DMA transfer.
With the existing code, after the DMA transfer PLDM unmaps
the memory and closes the file handler(XDMA FD).
Closing the XDMA file handler will reset the XDMA Driver which
internally will unmap the memory if not already unmapped.
But when the host crashes during the DMA transfer,
PLDM receives EINTR(interrupt) and it unmaps the memory.
XDMA driver doesn't know that the operation is interrupted,
it still thinks that operation is in progress.
munmap will hang if xdma driver thinks the operation is in progress.
To solve the PLDM Hang in munmap, in case of EINTR during DMA transfer
PLDM should skip munmap and just close the file handler.
Once PLDM closes the file handler driver gets reset and
it …
=> oem-ibm: Unmap the memory selectively

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
When PHYP toggles the PLDM_POWER_CYCLE_OFF_SOFT_GRACEFUL
we set the state manager property RequestedHostTransition
to ForceWarmReboot instead of Reboot, this will directly
reboot the host firmware without notification and chassis
power will remain on throughout the reboot, instead of
doing a graceful reboot
=> PLDM: Issue ForceWarmReboot instead if Reboot

oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json, oem/ibm/configurations/pdr/ibm,rainier-2u/11.json, oem/ibm/configurations/pdr/ibm,rainier-2u/4.json, oem/ibm/configurations/pdr/ibm,rainier-4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-4u/4.json
Verify identify effecter and identify effecter
-----------------------------
Rainier 1s-4u
---------------
sensor:
-------
}
{
"nextRecordHandle": 210,
"responseCount": 27,
"recordHandle": 209,
"PDRType": "State Sensor PDR",
"dataLength": 17,
"sensorID": 38,
"entityType": "[Physical] Connector",
"entityInstanceNumber": 1,
"containerID": 24,
"sensorInit": "noInit",
"sensorAuxiliaryNamesPDR": false,
"compositeSensorCount": 1,
"stateSetID[0]": "Identify State(17)",
"possibleStatesSize[0]": 1,
"possibleStates[0]": [
"Identify State Unasserted(1)",
"Identify State Asserted(2)"
]
}
effecter:
---------
{
"nextRecordHandle": 296,
"responseCount": 29,
"recordHandle": 295, …
=> PDR:Rainier: Add connector sensors & effecters

oem/ibm/configurations/bios/enum_attrs.json
oem-ibm : Add pvm_create_default_lpar bios attribute
=> oem-ibm : Add pvm_create_default_lpar bios attribute

common/types.hpp, common/utils.cpp, common/utils.hpp, libpldm/pdr.c, libpldm/pdr.h, libpldmresponder/fru.cpp, libpldmresponder/fru.hpp
This commit removes the duplicate sensor and effecter PDRs
that were present in our repo after the CM/hotplug.
tested the CM operation scenarios.
Fixes:SW548661
=> Remove the stale effecters and sensors after the CM

common/utils.cpp, common/utils.hpp, libpldmresponder/fru.cpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp
This function is added to support PCIe-Topology.
Util function takes Location code and Inventory Item Type
as inputs and return the dbus object path.
Tested:
Reset Reload operation and normal poweon workrs fine.
Also executed utility function with valid/invalid sets of input
and got expected results.
=> Utility to get object Path using location and inventory type

oem/ibm/libpldmresponder/platform_oem_ibm.cpp
In case of BMC reboot state manager starts after pldm,
so while sending bios attribute update event it doesn't get
boot progress state and causes exception. This is not considered
as error and pldm sends sends attribute update events to host.
So removed the trace.
=> [OEM]Remove misleading trace in case of BMC reboot

softoff/main.cpp
When we do a graceful shutdown of the host, the PLDM softoff app
does a setStateEffecter call on the Phyp's power down effecter,
after we receive the response for the same, softoff app starts a
timeout of 45 minutes for PHYP to finishing shutting down all its
services. The requirement is to request for a BMC Dump from the
PLDM softoff app when we hit this timeout and the Dump manager
should collect the BMC dump created.
Defect: SW549983
=> PLDM:SoftPowerOff request BMC dump during graceful shutdown

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
- When PDR exchange is completed with phyp, pldm will Query
HBRT and PHYP for the state of the host sensors in a recursive
loop. and in the middle of that recursion if some one power off the
system, the iterator is being corrupted and any access further using
the iterator would crash pldm.
TestedBy:
- Used automation test on the pldm change and it went successful without
any problem for  5 complete iterations of the test.
=> Fix pldm crash caused by corrupted iterator

oem/ibm/libpldmresponder/inband_code_update.cpp
The staging directory is created by the software manager application,
therefore it should not be deleted by pldm or it won't be re-created
until the next BMC reboot, and the inband update would fail with:
Apr 29 20:21:53 p10bmc pldmd[1980]: Cannot stat source directory
"/var/lib/phosphor-software-manager/hostfw/staging/lid" because No such
file or directory
Instead iterate over the contents of the directory to clear them.
Tested: The contents of the staging directory got removed, but not the
staging directory itself.
Change-Id: Id76ac325d49ca48891c99e7b71b1a0d5d64c85c3
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
=> oem: ibm: Do not remove the staging directory

oem/ibm/configurations/bios/enum_attrs.json
This commit is to remove petitboot from the pvm_rpa_boot_mode and
pvm_rpa_boot_mode_current attributes. For Everest and Rainier,
we do not need to support booting from petitboot, that was for
internal purposes only. To ensure that the petitboot option is
not an option on the GUI, it needs to be removed on the backend.
Defect SW547984:
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW547984
=> Remove Petitboot

host-bmc/host_pdr_handler.cpp, libpldmresponder/platform_state_sensor.hpp, libpldmresponder/test/libpldmresponder_platform_test.cpp
This commit sets the present and the event state of the sensors
same. when the led was turned on before R/R the sensor state is updated. 
After R/R event state of the sensor contains the changed state but the 
present state  was pointing to old state. the host was looking at the 
present state field of the sensor after the R/R.
- adds the setOperationStatus in createDbusObjects method
fixes - SW550014
=> fix to persist the indicator status after BMC R/R

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
In case of PLDM_POWER_OFF_HARD_GRACEFUL event PLDM shall update APR
and poweroff Chassis.
The OEM PowerDown effecter was defined to support 3 paths.
1. phyp initiated normal shutdown - PLDM_POWER_OFF_SOFT_GRACEFUL
2. phyp initiated re-ipl - PLDM_POWER_CYCLE_OFF_SOFT_GRACEFUL
3. phyp shutdown due to UPS event - PLDM_POWER_OFF_HARD_GRACEFUL
In all 3 cases, phyp has shut things down and is supposed
to be powered off.
When phyp receives the UPS event, phyp shuts things down
After phyp shuts down and sets the boot parms, phyp sets the OEM
PowerDown effecter to PLDM_POWER_OFF_HARD_GRACEFUL.
Then BMC should power off phyp.
=> [OEM_IBM]:Power off chassis in case of Hard Poweroff Event

host-bmc/host_pdr_handler.cpp, libpldmresponder/base.cpp, oem/ibm/libpldmresponder/collect_slot_vpd.cpp
the health status is marked as "OK" even for a FRU that is removed in MEX
but health status of removed FRUs in CEC would be marked as "Critical".
- fixes : SW549614
- also add debug traces in few parts of the code.
=> Workaround to mark the health status also as "Critical" for absent FRUs.

oem/ibm/configurations/fru/Chassis_VCEN.json, oem/ibm/configurations/fru/Motherboard_VCEN.json
Updated Json files to pick FC keyword from Dbus and type remains
the same as that of TM.
Tested using pldmtool
=> [OEM-IBM]Send TM keyword to PHYP reading FC keyword from Dbus

libpldmresponder/fru.cpp, libpldmresponder/fru.hpp
When a CEC FRU such as a Fan or Power Supply is concurrently removed,
BMC properly sends event to remove the FRU Record Set ID and to
modify the Entity Association PDRs.
BMC also removes the corresponding state sensors/ effecters PDRs.
However, BMC does not remove the FRU entry from the FRU Record Table
Modified code to delete FRU Record from FRU Record table.
Tested: Using busctl command and pldmtool
busctl set-property xyz.openbmc_project.Inventory.Manager
/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0
xyz.openbmc_project.Inventory.Item Present b false
pldmtool fru GetFruRecordTable -v
=> [PLDM FRU]: Removing FRU Record from FRU Record Table

host-bmc/dbus/pcie_device.cpp, host-bmc/dbus/pcie_device.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp
LanesInUse is changed from size_t to int64_t to cater for
unknown case, this PR would align pldm changes to the new PDI
change.
=> Change LanesInUse to int64_t

oem/ibm/requester/dbus_to_file_handler.cpp
This commit updates the Sign CSR error log severity to
informational as this should not be an unrecoverable error.
Fixes: SW550951
Change-Id: Iff1b33ea6e39781d31e069fa895c5c34455f80cd
=> oem-ibm: Changes the severity of Sign CSR error log

oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
Adding a check to check the host state is either
running or transitioningToOff, before creating the
error log if pldm fails to receive the surveillance ping
within the elapsed time of 120 seconds.
DEFECT:SW551173
=> PLDM: Check host state before logging PEL

oem/ibm/libpldmresponder/file_io.hpp
Currently there is no check for empty LicenseString
This commit adds check for empty license string.
This PR fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW544557#nle79
MUSTFIX approved
Tested By:
Set empty string to LicenseString D-bus property
=> Handle Empty LicenseString

host-bmc/dbus/custom_dbus.cpp, host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp
PHYP sends a sensor event on PLDM_STATE_SET_VERSION
state set to indicate that there is a change in the
mex io enclosure version.
This PR would react to the event and refresh the dbus
objects hosted by PLDM. This PR would also remove extra
unwanted traces.
Fixes : SW550806
=> Refresh dbus objects based on a signal from host

oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/service_files/pldm-create-phyp-nvram.service
The service needs to create the NVRAM file in the new hostfw directory.
Change-Id: Ia018c6e96efa763934d8ae8969f893eb0bb1ffad
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
=> oem: ibm: Fix pldm-create-phyp-nvram.service

host-bmc/host_pdr_handler.cpp, host-bmc/test/utils_test.cpp, libpldm/meson.build, libpldm/pdr.c, libpldm/pdr.h, libpldm/pdr_data.h, libpldm/tests/libpldm_pdr_test.cpp, libpldmresponder/fru.cpp, libpldmresponder/pdr_state_sensor.hpp, oem/ibm/libpldm/pdr_oem_ibm.c, oem/ibm/libpldm/pdr_oem_ibm.h, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
In MEX systems, PLDM receives multiple refresh repo events from host.
After receiving refresh repo event, PLDM delete the host PDRs except the
Entity association PDRs and then fetches list of PDRs from host again.
In this scenario PDRs are added such a way that it causes loop.
Fixed the issue by merging Entity association PDRs(from Phyp) in the BMC range.
Following are the modification:
Using record handle 0xFFFFFFFF to mention that PDR has to be added to
BMC range
Modified oem function to traverse the complete repository and get the
latest BMC PDR
For MEX CM - whenever connectors are present under the card and a
CM is done on the card, it was not handled properly and PHYP task
would crash. With this changes it is fixed.
Tested:
Tested using pldmtool and busctl command
pldmtool platform …
=> fixes MEX CM and looping issue in MEX systems

oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
ImageActivation match which is reset even before we receive
the Image Active signal is received. Which is why we are
failing to send the End update sensor event to PHYP. This
needs to be reset only after the end update success/failure
event to PHYP after receiving the Active signal on the activation
property.
Defect:SW551662
=> PLDM: Reset image activation after sending end update event

softoff/services/pldmSoftPowerOff.service
Saw an interesting issue recently where the system ended up in a
situation where the pldmSoftPowerOff application was running through an
entire reboot of the host firmware.
Another bug induced the issue, but basically the pldmSoftPowerOff
service was waiting for the host to indicate it had shutdown, when in
fact the host had already been stopped and the system was rebooted. The
reason the pldmSoftPowerOff service was not stopped on the reboot of the
host is because it conflicts with the incorrect target. The
obmc-host-start@.target is only run on fresh boots of the system. The
obmc-host-startmin@.target is called on all boots, including reboots.
To ensure pldmSoftPowerOff is always stopped when the host is being
booted, change the conflicts.
Signed-off-by: Andrew Geissler …
=> softoff: ensure stopped on any boot of host

host-bmc/utils.hpp
Tested By:
1. With change powered on the system
2. Checked that pldm generated the dbus object for CMC FRU
3. Checked that pldm generated the dbus object for CMC LED's
4. Checked the redfish Assembly schema & found the CMC with the
correct location code.
Fixes : SW551748
=> Change the entity type for CMC from 63 to 62

host-bmc/utils.hpp, oem/ibm/configurations/pdr/ibm,everest/11.json, oem/ibm/configurations/pdr/ibm,everest/4.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json, oem/ibm/configurations/pdr/ibm,rainier-2u/11.json, oem/ibm/configurations/pdr/ibm,rainier-2u/4.json, oem/ibm/configurations/pdr/ibm,rainier-4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-4u/4.json, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
These changes are required to toggle the LEDs for unpopulated
Procs and DIMMs
Irrespective of whether a DIMM or ProcessorModule is present,
host will always send Memory Board & Physical Socket.
Memory Module(DIMM) is under Memory Board entiity and
Processor Module(DCM) is under Physical Socket entity.
From pldm side, we modify the above mentioned led PDR's
with the same entity type, instance number & container id for both
Memory Board entity and Physical Socket entity from hostboot.
Fixes: SW551210
Change-Id: Ifb8ae517270fe34bb1c54770d4c96ed453f395bb
=> oem-ibm: Create LED PDRs for unpopulated DIMMs and Procs

host-bmc/host_pdr_handler.cpp, libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This commit is to disable the timer when we fail
to receive the surveillance pings from PHYP.
DEFECT:SW551173
=> PLDM: Disable surveillance timer

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json, oem/ibm/configurations/bios/string_attrs.json
These BIOS attributes needed for enabling IPv6 on VMI interfaces
Signed-off-by: Ravi Teja <raviteja28031990@gmail.com>
Change-Id: I90bc815bb5aa303c9fa40be500469592ec0ffb64
=> Add VMI IPv6 BIOS attributes

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/linkreset.cpp, host-bmc/dbus/linkreset.hpp, host-bmc/host_pdr_handler.cpp, host-bmc/test/meson.build, libpldm/states.h, libpldmresponder/meson.build, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp
This commit implements the link reset feature support
for both primary and secondary links.
When the link reset property is set to true, a host
stste effecter is triggered.
Tested using busctl commands.
=> PLDM Topology : PCIe Link Reset support

configurations/host/host_fru_associations.json, host-bmc/dbus/led_group.cpp, host-bmc/dbus/led_group.hpp, host-bmc/dbus_to_host_effecters.cpp, host-bmc/host_pdr_handler.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp
This PR would contain the below changes:
1. Every mex fan out module will be now under a logical pcie slot.
2. Every fanout module is now both a fabric adapter & also a pcie device
3. The newly added logical pcie slots(with oem slot type) is associated
to the mex chassis.
=> PCIeTopology : Parse special links & set the topology information

libpldmresponder/platform.cpp, oem/ibm/configurations/pdr/ibm,everest/4.json, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commit fixes the issue of missing fault led indicator sensors
for the cable card ports (pcie slot 8). The sensors were not
getting generated due to the incorrect inventory paths.
Tested the changes in an everest system.
Fixes: SW552427
Change-Id: I5fb43d9780fedd06cb407884d85b9e10b4dee1ef
=> Fixes the missing fault led indicator sensors

oem/ibm/configurations/bios/enum_attrs.json
Add the newly supported values of logic memory block size under
the bios attribute hb_memory_region_size.
Fixes: LI 02N requirement
Change-Id: I12d990440f4c006dab0d303594fb9f99d2df28b0
=> oem-ibm: Add support of new LMB sizes

pldmd/instance_id.cpp, pldmd/instance_id.hpp
With this commit PLDM will :
1. Keep the timestamps for every instance id.
2. When all the instance ids are exhuasted , then pldm will
look at the oldest instance id and release it.
3. pldm will only crash if none of the instance id's are older
than the instance_id_expiration time.
=> Release the oldest instance id when all the instance ids are exhausted

oem/ibm/configurations/pdr/ibm,everest/11.json, oem/ibm/configurations/pdr/ibm,everest/4.json
This commit fixes the issue of wrong dbus mapping of identify and
fault processor leds in the everest system.
Fixes: SW552819
Change-Id: Iafc0ee751864c3d8ababf1184afadb6dd3a433b6
=> oem-ibm: Fix the everest processor led sensor mappings

configurations/events/stateSensorPdrs.json
This commit skips the usage of container ids for dimms in the
state sensor events json file so that correct dimm will get
deconfigued after applying a gauard operation.
Tested: Applied manual guard to ramdom dimms and observed that
correct/required dimms get deconfigured during/after the IPL.
Fixes: SW553011
Change-Id: I3d205b55b7b95ab607b53e3e82d18c7e8a5f0a5e
=> sensor-events: Fix to deconfigure the dimms correctly

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/linkreset.cpp
lanesInUse is recently changed to int64_t from size_t to
be able to show the unknown case (using -1 value). There
are certain parts of pldm code that have not completed the
migration and the value is implicitly being converted to an
unsigned number. This would fix the behavior.
This PR would also fix some traces in pcie linkreset.
=> Fix lanesInUse to be an int64_t value

libpldmresponder/platform_state_sensor.hpp
PLDM sensor state of the enclosure fault/identify led is not
displayed correctly when its On/Blink. Added special handling of
sensor state when the property value contains logical OR operator.
Tested: Tested the sensor values of enclosure fault/identify by
setting On, Off and Blink values.
Fixes: SW552922
Change-Id: Ie65217a0dfec393da1e3de26a7a6416860037bdc
=> pldmresponder: Fix sensor state of enclosure fault/identify led

oem/ibm/configurations/bios/integer_attrs.json
This commit is to change the range of values for
IO Enlarged Capacity value to be set on the GUI from
max PCI slots of Rainier system to the max value across
different platforms(rainier/everest)
Defect: SW552828
=> PLDM: Change the max value of hb_ioadapter_enlarged_capacity

oem/ibm/libpldmresponder/file_io.cpp
These changes will handle the case where host crashes in the
middle of outofband DMA transfer during system dump offload.
When the host crashes during the DMA transfer,
PLDM receives EINTR(interrupt) and it unmaps the memory.
XDMA driver doesn't know that the operation is interrupted,
it still thinks that operation is in progress.
munmap will hang if xdma driver thinks the operation is in progress.
=> oem-ibm dump offload :Avoid Unmap of DMA on EINTR error  

oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This is commit fixes the PLDM hang happened during DMA operation.
If the BMC had operations queued up in DMA engine and host goes to
off/transitioning to off state,operations are “stuck” and
pldmd hangs on ongoing operation.
Now we are not initiating any DMA transfer if host state is
off/transitioning to off.
Tested:
Tested using below steps
1. busctl command to change the hoststate to offbusctl set-property
xyz.openbmc_project.State.Host /xyz/openbmc_project/state/host0
xyz.openbmc_project.State.Host  CurrentHostState s
"xyz.openbmc_project.State.Host.HostState.Off"
2. Initiate DMA operation using curl command or using topology file transfer
3. Looking at the traces confirmed that DMA is not initiated
=> [PLDMFileIO]Do not initiate DMA OP if host is in off state

oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This reverts commit a3dd6293628a145464f4ca38b97d454d16871e4c.
This caused unexpected issues with the host being unable to flush its
NVRAM to the BMC during the graceful shutdown.
Fixes SW553535
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
=> Revert "[FileIO]Do not initiate DMA OP if the hoststate is off (#280)"

oem/ibm/service_files/meson.build, oem/ibm/service_files/pldm-clear-dma.service
In the current state , the DMA infrastruture written in pldm
is blocking IO, due to pldm operating in blocking mode there
are cases where pldm hangs in read/write system calls due to
multiple reasons like :
1. Stray DMA message in mctp buffer
When DMA operations in progress with PHYP and it goes down
abruptly, the DMA command of PHYP could be stored inside
the mctp buffer and that can be delivered to Hostboot(which does
not have pcie support) leading to a pldm hang.
2. PHYP crashes while a DMA transaction is in progress
xdma driver on bmc does not have a way to know if host had gone
down due to crash , so the outstanding DMA operation that is
currently running would be left hanging, leaving pldm to hang
as well.
Added new service pldm-clear-dma.service which would send
signals (SIGSTOP, …
=> Add a new service the clear's the stray DMA transactions

oem/ibm/libpldmresponder/utils.cpp
DMA unmap is missing in error path causing DMA leak.
This commit fixes this DMA unmap issue in socket error handling.
This PR fixes https://w3.rchland.ibm.com/projects/bestquest/?defect=SW553672
=> oem-ibm dump offload :Unmap the DMA memory in error path

oem/ibm/libpldmresponder/utils.cpp
There was a time where we were not able to find the
presence of the nvme drives on IBM systems,to work
around that pldm was looking at the parent of the drive
which is the nvme slot to figure out the presence of the
drive.
Now that we had code in platform-fru-detect which can
detect the presence of nvme drives over nvme-MI, the
workaround that we put to look for drives parent presence
is no longer needed. This PR is an attempt to fix that.
=> Don't discard the nvme drive presence

oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/inband_code_update.hpp
Wait on the Software Updater before getting the Association endpoints,
during the code update as there maybe delays in BMC software
updater.
Defect:SW554311
=> PLDM:Wait on the Software Updater

oem/ibm/libpldmresponder/file_io_type_pcie.cpp
pldm is confused between the flett links that has the flett
involved (io_slot location codes are cec slots) & the links
that involve pcie switch on the cable card(io_slot location
codes are mex slots).
So the fix is to first check if the local ports are on the
cec first, and if not, then check for mex so that we populate
both the flett and the links that capture the pcie switch on the
cable card.
=> Fix topology links for flett and pcie switch

oem/ibm/configurations/bios/integer_attrs.json
1. Remove hana from hb_cap_hana_freq_mhz attributes
https://gerrit.openbmc.org/c/openbmc/pldm/+/55494
2. Support BIOS control of max freq setting (for HANA)
https://gerrit.openbmc.org/c/openbmc/pldm/+/54667
=> PLDM: SAP HANA

softoff/services/pldmSoftPowerOff.service
openbmc/phosphor-state-manager#21 highlights an architecture issue with
OpenBMC's use of synchronization targets. When a service, such as
pldmSoftPowerOff.service, runs both in a standard power off
target, as well as in other paths (like the host graceful quiesce
path), there is an issue.
The service starts the synchronization targets in the quiesce path and
this causes them to already be running on the power off, resulting in
the synchronization targets not actually coordinating the power off.
The direction this commit takes OpenBMC is that if a service needs to
run outside of the standard power on or off path, then they can not
have a Wants or Requires clause in the service file.
The following commit was done a while back to address this issue: …
=> remove wants on synch targets in soft off

oem/ibm/configurations/bios/enum_attrs.json
This commit adds Proc Favor Aggressive Prefetch, as an enumeration, to the BMC BIOS.
Add boths a current value and a pending value.
The enumeration fields are Enabled and Disabled.  The default is Disabled.
RTC: 339426
Change-Id: I1bf40275cc22ae81011d19e7be31d92c2d508f0f
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
Conflicts:
oem/ibm/configurations/bios/enum_attrs.json
=> Adds Proc Favor Aggressive Prefetch to the BMC BIOS

oem/ibm/configurations/bios/enum_attrs.json
This commit adds Proc Favor Aggressive Prefetch, as an enumeration, to the BMC BIOS.
Add boths a current value and a pending value.
The enumeration fields are Enabled and Disabled.  The default is Disabled.
RTC: 339426
Change-Id: I1bf40275cc22ae81011d19e7be31d92c2d508f0f
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
Conflicts:
oem/ibm/configurations/bios/enum_attrs.json
Co-authored-by: Deb McLemore <debmc@linux.ibm.com>
=> Adds Proc Favor Aggressive Prefetch to the BMC BIOS (#301)

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, libpldmresponder/oem_handler.hpp, libpldmresponder/platform.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This commit persists the HB range PDRs in the repo before
they are merged. This change was needed as PHYP would not send
down BMC the entity Association PDRs of HB after a R/R as the
PDRs will be in BMC range of record handles. Due to this
the pldm ebmcModel in the PHYP was not updated properly.
This commit also prevents adding duplicate terminus locator
PDRs to the repo.
Tested: Multiple poweron and  poweroff
Multiple Reset Reloads
Fixes: SW553100
=> PLDM: Changes to persist the HB PDRs in the repo before merging

libpldmresponder/fru.cpp
Issue is seen when skiboot sends GetRecordByOption command during IPL
On receipt of GetRecordOption command, PLDM traverses through fru table
and copies the records matching the Record type and record set identifier
and field type.
We are sending table size to the library function which will
return the expected records. As the wrong table size is sent to
the lib function, code crashes while traversing the fru table.
Corrected the table size sent to library function to get record by option.
Fixes SW554881
Tested:
Tested using pldmtool commands at different IPL stages.
pldmtool fru GetFRURecordByOption -i 1 -r 1 -f 0
=> [FRU]Fixed issue in processing GetRecordByOption

oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, tools/visualize-pdr/pldm_visualise_pdrs.py
In the current state pldm would just drop the link that
has the link type as Unknown, the intent behind this PR
would be to add in necessary support in pldm so that we
store the last link type of a link and use for setting
the topology information.
Tested By:
1. Power on the host, make sure we are at Standby.
2. Get topology information and make sure all the links
are populated correctly.
3. Inject the error on a link using phyp macros 5 times untill the
link is dead
xmwritereg -mmio -drc 20000010 -offset C00 -length 8 -asb -data 8000000000000000
xmtest -slotErrorRecovery 21010010 19
4. Refresh the topology page and make sure the link is
populated and with accurate information.
=> Fix support for link with Unknown Type

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commit changes the state set id of the host state effecter
that is used for the SBE dump status update.
Fixes - SW554759
=> PLDM: SBE Host effecter state set id change

host-bmc/dbus_to_event_handler.cpp, host-bmc/dbus_to_event_handler.hpp, libpldmresponder/pdr_utils.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform_state_sensor.hpp, libpldmresponder/test/libpldmresponder_platform_test.cpp
In the current state, any sensor event from the bmc pldm
stack would have the same value for both the previous state
and the event state. This commit would fix that behaviour
by caching the previous state.
This commit would also add the previous state support for the
state sensor reading reply as well.
Tested By :
1. Change the value of sensor using busctl for example dimm8 identify
to false
Tx: 81 02 0a 01 00 00 4d 00 01 00 [ 01 00 ]
Note that the very first event for every sensor would have the previous
state as PLDM_SENSOR_UNKNOWN [0]
In the above example : [ event state : 01 , previous state : 00 ]
2. Change the value of dimm8 identify to true
Tx: 81 02 0a 01 00 00 4d 00 01 00 [ 02 01 ]
[ event state : 02 , previous state : 01 ]
3. Change the value of dimm8 identify to false
Tx: 81 02 …
=> Add support for previous state in the event messages

host-bmc/dbus_to_event_handler.cpp, host-bmc/dbus_to_event_handler.hpp, libpldmresponder/pdr_utils.hpp, libpldmresponder/platform.hpp, libpldmresponder/platform_state_sensor.hpp
The crash is due to accessing the vector events for composite sensors.Fixed it by using a predefined array that is initialised with 0.
=> Fix pldm crash due to previous events

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
The fix that we had put up didn't pass the Everest HW CI. To fix SW553100 we need changes 
from HB and not only from BMC. This commit reverts the change made.
It was tested on both rainier and Everest systems.
=> Reverting the change to persist HB Entity Association PDRs

libpldm/tests/libpldm_pdr_test.cpp, libpldmresponder/fru.cpp, oem/ibm/libpldmresponder/fru_oem_ibm.cpp
This commit fixes:
1. PLDM Test cases fixed
- pldm_pdr_find_record test cases are fixed
2. Combining multiple repository change events
- When the FRU is concurrently added/removed, PLDM would
add/remove all the Sensors/Effecters/Fru Records
attached to the FRU and also the the necessary
entity association PDR's would be modified.
For the PDRs changes Removed/Added/Modified
is informed to Host through mutiple repository change events.
sending multiple Remove/Add/Modify events to PHYP
causes high traffic to PHYP in small amount of time.
In CMC exchange case PHYP triggers multiple slot
enable/disable effecter which is causing multiple
repository change events to PHYP. As PHYP's queue size is 32
its not able to handle all respository change events
received within seconds. To reduce the …
=> PLDM: Combining multiple repository change events

oem/ibm/host-bmc/host_lamp_test.cpp
This commit contain:
- lamptest should complete in 4 min and after that asserted property of host and
LED manager will be reset to false. but only LED manager asserted property
was getting reset to false but host asserted property was remain true which is fixed
with this fix.
- Fix of defect SW557624
=> PLDM: Host lamp test asserted property not getting reset after lamp test finished.

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json, oem/ibm/configurations/bios/string_attrs.json
- Attribute made as readOnly as per Defect SW557487
- List of attributes are modified as readOnly:
hb_cap_freq_mhz_request_current
hb_field_core_override_current
hb_host_usb_enablement_current
hb_huge_page_size_current
hb_key_clear_request_current
hb_lateral_cast_out_mode_current
hb_memory_mirror_mode_current
hb_memory_region_size_current
hb_mfg_flags_current
hb_number_huge_pages_current
hb_power_limit_enable_current
hb_proc_favor_aggressive_prefetch_current
hb_tpm_required_current
pvm_create_default_lpar_current
pvm_default_os_type_current
pvm_os_boot_type_current
pvm_rpa_boot_mode_current
pvm_stop_at_standby_current
pvm_vtpm_current
=> PLDM: Mark all _current attributes as readonly

oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp
Topology/cables data received from host is written in a file by BMC. Data received after refresh is appended to the same file causes stale data fetched during DBus Object update.
Removing the topology file and cable attributes file just before receiving refreshed data so that latest data gets saved in the file.
Fixes: PE00DPCM
Tested:
Fetching/Refreshing Topology data:
All the links/data were populated correctly.
Topology and cable files were deleted and created on every refresh.
=> Removing topology and cable files before refresh

oem/ibm/libpldmresponder/inband_code_update.cpp
This commit adds additional tracing to print the
exception along with the error message in the we hit an exception while waiting for the Software Activation property.
=> oem-ibm : Code update FFDC enhancement

libpldmresponder/bios_enum_attribute.cpp, libpldmresponder/bios_integer_attribute.cpp, libpldmresponder/bios_string_attribute.cpp
Discard the persisted attribute value if the bios attribute value doesn't fall in the range provided by the current firmware level. In current implementation we restore the persisted attribute value without validation for string and integer attributes and in case of enum attributes we just throw error and don't add the attribute in the table if it fails.
This causes multiple unrecoverable errors getting logged during IPL if there is change in bios attribute details between old and new firware levels.
To fix the issue added changes to validate the persisted value before restoring it during power on.
Added the check for Integer, String and Enum attributes. Setting it to the default value if the validation of persisted value fails.
Fixes PE00DYMM
Tested:
Below are the tests performed
1. …
=> Discard attribute persisted value

host-bmc/host_pdr_handler.cpp
This bug was introduced due to SW553100 changes where we started adding correct terminus handles to entity association PDRs in our repo. Due to this when we get a refreshEntireRepository repo change event from PHYP, BMC removes all the PHYP PDRs including the entity association PDRs. The BMC entity tree is untouched.
When a MEX drawer is powered on back, our code just checks the BMC entity tree for the entity and if its present we skip adding the PDR to the repo. This leads to BMC reusing some of the PDR record handles and PHYP asserts as it doesn't handle it.
Unit tested below scenarios:
- PowerOn and PowerOff
- ResetReload
- CEC Hotplug and CEC CM
- MEX CM
Fixes: SW558361
=> Fix to handle PHYP hang after a MEX drawer CM

oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp
This commit clears SocketWriteStatus to "Free" when host power off
which avoids any wrong dump offload socket write status in  error cases
This PR fixes  race condition of status values across back to back MPIPLs 
when dump offload abruptly interrupted by power off 
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW558457
=> DumpOffload: Clear SocketWriteStatus when Host poweroff

oem/ibm/libpldmresponder/inband_code_update.cpp
Remove redundant calls to get Activation status property, This call times out which is a "get property" dbus call which result is not being used in the code.
DEFECT: PE00F24K
=> oem-ibm: Remove redundant calls to get Activation status

host-bmc/dbus/custom_dbus.cpp, host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp
Received incorrect PCIe topology information because of the wrong PLDM Cache, so deleting the PLDM cache for every IPL.
Unit tested below scenarios:
- PowerOn and PowerOff
- ResetReload
Fixes SW558000
=> Remove Mex Dbus objects and persisted details during IPL

host-bmc/dbus/custom_dbus.cpp, host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp
```
Received incorrect PCIe topology information because of the wrong
PLDM Cache, so deleting the PLDM cache for every IPL.
Unit tested below scenarios:
- PowerOn and PowerOff
- ResetReload
Fixes SW558000
```
=> 1050: Remove Mex Dbus objects and persisted details during IPL

oem/ibm/configurations/fru/Motherboard_PSPD.json
This commit supports the new VPD record called PSPD under the backplane FRU vpd. Keywords RT, PF, VM and VZ are added under the PSPD VPD record so that host can consume. Change is being added as part of LI OMX new Bonnell system support.
Fixes: Jira Story PFEBMC-16
Change-Id: Id2b357719970c3bd4c52732da467af307e48e183
=> oem-ibm: Support of new PSPD VPD record

oem/ibm/configurations/pdr/ibm,bonnell/11.json, oem/ibm/configurations/pdr/ibm,bonnell/4.json
LED Sensor and Effecter PDR support for Bonnell. This commit adds the JSON files that describe LED sensor and effector entity path and dbus properties for Bonnell.
Signed-off-by: Varsha Kaverappa <vkaverap@in.ibm.com>
=> PLDM BONNELL : LED Sensor & Effecter PDR support in PLDM

oem/ibm/configurations/bios/enum_attrs.json
Add the newly supported values of memory region aka "Logical Memory Block" size under the bios attribute hb_memory_region_size.
Fixes: LI 02N requirement
Change-Id: I4f35a647e829d64abfa6dd59b2b1070a47a37a20
=> oem_ibm: Add new memory region sizes

oem/ibm/configurations/pdr/ibm,everest/4.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json, oem/ibm/configurations/pdr/ibm,rainier-2u/4.json, oem/ibm/configurations/pdr/ibm,rainier-4u/4.json, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
```
Physical SAI (System Attention Indicator) led state was not
getting notified to PHYP. This commit models the physical SAI led
sensor so that whenever any change in the state happens, PLDM
sends the sensor state change event to PHYP.
Fixes the defect: SW559304
Tested below scenarios:
1. Turning On/Off the effecters of virtual platform/partition SAI
2. Changing dbus properties of virtual platform/partition SAI
3. Turn off real SAI led using effecter
Change-Id: Ib11945096b3e031cf5412b74f4256915017f999c
```
=> 1030: oem_ibm: Fix SAI led notify issue

oem/ibm/configurations/pdr/ibm,bonnell/4.json, oem/ibm/configurations/pdr/ibm,everest/4.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json, oem/ibm/configurations/pdr/ibm,rainier-2u/4.json, oem/ibm/configurations/pdr/ibm,rainier-4u/4.json, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
Physical SAI (System Attention Indicator) led state was not getting notified to PHYP. This commit models the physical SAI led sensor so that whenever any change in the state happens, PLDM sends the sensor state change event to PHYP.
Fixes the defect: SW559304/STGDefect395326
Tested below scenarios:
1. Turning On/Off the effecters of virtual platform/partition SAI
2. Changing dbus properties of virtual platform/partition SAI
3. Turn off real SAI led using effecter
Change-Id: I6b2b54d3844eb90f42b7d3c0e8d7fab04c8d45c3
=> oem_ibm: Fix SAI led notify issue

configurations/events/stateSensorPdrs.json
This change was made in 1030 to skip the usage of container id for dimms in the state sensor events json file so that correct dimm will get deconfigued after applying a gauard operation.
=> PLDM: Some more missed changes in 1050.

configurations/events/stateSensorPdrs.json, pldmtool/pldm_platform_cmd.cpp
Adding support for new bootprogress state
Adding new bootprogress state which indicate system firmware
or BIOS is starting the operating system at the point of time.
This new bootprogress state is taken from
PLDM stateset(DSP0249) design spec and stateset id is 196.
=> Adding Enum to support boot progresscode changes

oem/ibm/configurations/fileTable.json
```
Add the new Planar SPD lid files for platforms.
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
Signed-off-by: Deb McLemore <debmc@us.ibm.com>
```
=> 1050: Hostboot Add Planar SPD lid files for platforms (#338)

configurations/pdr/11.json
This commit adds the maximum settable value for the boot counter numeric effecter. 
The value is set to the current default value as per the PDI -
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Control/Boot/RebootAttempts.interface.yaml
=> Adding max settable value for boot counter effecter

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json
- Adding bios attributes for runtime processor diagnostics
feature which allow HOST to consume bios attribute at
runtime and after that it's depend on HOST decision to
apply immediately  or next IPL cycle.
=> Adding bios attributes for RPD feature

libpldmresponder/base.cpp, libpldmresponder/test/libpldmresponder_base_test.cpp
This commit fixes the GetPLDMVersion command core
dumping when run using pldmtool.
Tested: Patched the changes and verified the pldmtool command
=> Fix the GetPLDMVersion command core dump

configurations/pdr/11.json
The D-Bus path for the ScheduledTime property had to change. The details of this can be found over in the change:
https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/61361
Update PLDM to utilize this new object path.
Change-Id: I89fdb603730ea3569db03d136a31fef0988cd5bb
=> scheduled_host_transition: new object path

oem/ibm/libpldmresponder/file_io_type_vpd.cpp
The length of the data in response msg was more than the actual keyword size when hostboot requested for #D keyword data. This commit fixes the issue and also includes one additional trace for debug purpose.
=> BONNELL PLDM : Fix for #D file I/O support

configurations/host/host_fru_associations.json, host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/panel.hpp, host-bmc/host_pdr_handler.cpp, host-bmc/utils.hpp, libpldmresponder/platform.cpp
This PR adds the following dbus models for the fru's on splitter drawer:
1. ESM Module(PLDM_ENTITY_BOARD) is modelled as Item.Board and the necessary association definitions are added to the associations json file ,so that ESM could be listed as a redfish assembly.
2. LED Panel Board(PLDM_ENTITY_CHASSIS_FRONT_PANEL_BOARD) is modelled as Item.Panel and the necessary association definitions are added to the associations json file, so that the LED Board could be listed as a redfish assembly.
3. Temperature Sensor(PLDM_ENTITY_EXTERNAL_ENVIRONMENT) is modelled as Item.board and the necessary association definitions are added to the associations json file, so that the Temperature sensor could be listed as a redfish assembly.
Tested By:
1. Powered on the Splitter & found the ESM and also LED …
=> Add dbus model for fru's on splitter (#376)

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json, oem/ibm/configurations/bios/string_attrs.json
Pull request: https://github.com/ibm-openbmc/pldm/pull/381
Upstream: https://gerrit.openbmc.org/c/openbmc/pldm/+/61015/15
Fixes: 421850 : PLDM flooding trace log on BMC.
Port to: FW1050
=> Adding PLDM bios power supply attributes

oem/ibm/configurations/bios/enum_attrs.json
BMC present means function.
Change-Id: I4bb8985c43f54dadf85a92c96cc81a402cfaa4a5
Change-Id: I32f4075adbc7182ddb128176031287b0b0169c19
Signed-off-by: Sheldon Bailey <baileysh@us.ibm.com>
=> Change PLDM power supply bios attribute to get present instead of functional.

oem/ibm/configurations/bios/enum_attrs.json
This commit removes the duplicate BIOS attribute
entries from the JSON. This commit also adds
ReadOnly field to the _current attributes that were missed earlier.
=> Remove the duplicate BIOS attribute entries

libpldmresponder/base.cpp
This commit removes the creation of PEL
in the host watchdog path when host boot
replies with ENABLE_METHOD_NOT_SUPPORTED.
=> Remove PEL creation in watchdog path

libpldmresponder/bios_config.hpp
PLDM was just watching for PropertiesChanged signals on the D-Bus properties that back BIOS attributes.  Just doing that can miss properties on interfaces that get added after PLDM starts and then never change after that, because they would just send a single InterfacesAdded signal.
Close that hole by also adding an InterfacesAdded match along with the PropertiesChanged match.
Change-Id: Iab6679b0c99d049bd5f11e6508f784b2e8eb9349
=> Listen for ifacesAdded for BIOS attribute props

libpldmresponder/bios_config.hpp
```
PLDM was just watching for PropertiesChanged signals on the D-Bus
properties that back BIOS attributes.  Just doing that can miss
properties on interfaces that get added after PLDM starts and then never
change after that, because they would just send a single InterfacesAdded
signal.
Close that hole by also adding an InterfacesAdded match along with the
PropertiesChanged match.
Change-Id: Iab6679b0c99d049bd5f11e6508f784b2e8eb9349
Signed-off-by: Matt Spinler <spinler@us.ibm.com>```
=> 1050: Listen for ifacesAdded for BIOS attribute props (#389)

oem/ibm/configurations/bios/integer_attrs.json
This change updates the lower_bound value of
vmi_if0_ipv6_prefix_length and vmi_if1_ipv6_prefix_length
to 0 from 1.
Upstream commit : https://gerrit.openbmc.org/c/openbmc/pldm/+/62470
Tested by:
curl -k -H "X-Auth-Token: $bmc_token" -XPATCH -D patch.txt -d '{"IPv6StaticAddresses": [{"Address": "2002:903:15f:325:123:123:123:124","PrefixLength": 0}]}' https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1
curl -k -H "X-Auth-Token: $bmc_token" -X GET -D patch1.txt https://${bmc}/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1
{
"@[odata.id](http://odata.id/)": "/redfish/v1/Systems/hypervisor/EthernetInterfaces/eth1",
"@odata.type": "#EthernetInterface.v1_8_0.EthernetInterface",
"DHCPv4": {
"DHCPEnabled": false
},
"DHCPv6": {
"OperatingMode": "Disabled"
},
"Description": …
=> PLDM: Update lower_bound of ipv6_prefix_length to 0

configurations/host/host_fru_associations.json, host-bmc/host_pdr_handler.cpp
PDI has new association names(powering, powered_by) for PSUs. So making the changes in PLDM so that redfish client shall be able to access it.
Tested:
Fetched PowerSupplies under MEX using redfish GET query. Received the expected response.
=> Modify Mex PSU associations

oem/ibm/configurations/bios/enum_attrs.json
Adding host controlled VMI support bios attribute
for HMC Enablement Control for eBMC based systems.
=> Adding bios attributes for VMI Support

host-bmc/dbus_to_event_handler.cpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/base.cpp, libpldmresponder/base.hpp, libpldmresponder/fru.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
Hardcoded terminus id 0 is used at multiple places in the current code. Made changes to populate correct terminus id instead of hardcoded one.
=> Populate correct Terminus Id

oem/ibm/service_files/pldm-clear-dma.service
Upstream yocto introduced a change via e510222 (systemd-systemctl: fix instance template WantedBy symlink construction).
This fixes a bug that we in OpenBMC had been taking advantage of in that we were able to document our templated target dependencies without it actually doing anything. The real installation of services within targets occurs in our bitbake recipes due to the complexity of chassis and host instances on a per machine basis.
Leave the dependency information in the service files but comment them out. It's useful to be able to look at a service and understand which targets it's going to be installed into by the bitbake recipes.
In some cases, we had hard coded the target instance, which does install the service correctly, but only in that one target. All services should be …
=> systemd: no installation in templated targets

oem/ibm/libpldmresponder/file_io_type_lid.hpp
This commit adds changes to call the validate API
from phosphor-software-manager to validate the
marker lid. And further send the status of the validation to PHYP through a sensor event.
=> Marker Lid validate for Inband updates

oem/ibm/configurations/fru/Motherboard_UTIL.json
This commit adds new UTIL record keywords RT, F5 and F6 under the motherboard. F5 and F6 keywords are used to fill up the desired host splash screen name displayed at the host console.
Resolves: ibm-openbmc/dev#3616
Tested: Verified that the name filled up through the F5 and F6 keywords are displayed at the host splash screen
Change-Id: I26f1c03db3e9f6a5b8cdc435d9e80d7c92563e16
=> oem-ibm: Support new UTIL keywords

host-bmc/dbus_to_host_effecters.cpp, oem/ibm/libpldmresponder/platform_oem_ibm.cpp
Two merged upstream commits to remove OSStart from PLDM:
- https://gerrit.openbmc.org/c/openbmc/pldm/+/63138
- https://gerrit.openbmc.org/c/openbmc/pldm/+/63139
=> 1050 no osstart

oem/ibm/configurations/fru/Motherboard_UTIL.json
```
This commit adds new UTIL record keywords RT, F5 and F6 under the
motherboard. F5 and F6 keywords are used to fill up the desired
host splash screen name displayed at the host console. The RT
keyword is used to hold the record name.
Resolves: ibm-openbmc/dev#3616
Tested: Verified that the name filled up through the F5 and F6
keywords are displayed at the host splash screen
Change-Id: I26f1c03db3e9f6a5b8cdc435d9e80d7c92563e16
Signed-off-by: Jayashankar Padath <jayashankar.padath@in.ibm.com>```
=> 1030: oem-ibm: Support new UTIL keywords (#419)

host-bmc/host_pdr_handler.cpp
Removing the size of `struct pldm_msg_hdr` from the buffer size is already accounted for in pldmd/pldmd.cpp:processRxMsg().
The double accounting leads to a failure to decode the message in libpldm as the buffer appears too short. With assertions enabled in libpldm (as it's currently not feasible to disable them) we arrive at the following abort and (abbreviated) backtrace:
```
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=<optimized out>) at pthread_kill.c:44
44      pthread_kill.c: No such file or directory.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=<optimized out>) at pthread_kill.c:44
#1  0x76403a14 in __GI_raise (sig=sig@entry=6) at …
```
=> Fix double-accounting for `struct pldm_msg_hdr` in `getPresentStateBySensorReadigs()`

oem/ibm/configurations/bios/enum_attrs.json
```
Traditional IBM systems since 1988 used to ship with A_Mode
as the default partition mode for iBMi. Changing the default
value from D_Mode to A_Mode to match the behaviour of our systems
and align them with the earlier behaviour.
```
=> 1020: Change the default partition mode to A_Mode (#420)

oem/ibm/configurations/bios/enum_attrs.json
```
Traditional IBM systems since 1988 used to ship with A_Mode
as the default partition mode for iBMi. Changing the default
value from D_Mode to A_Mode to match the behaviour of our systems
and align them with the earlier behaviour.
```
=> 1030: Change the default partition mode to A_Mode (#420)

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commits adds change to check for the customer PowerRestorePolicy before setting the one_time
PowerRestorePolicy when PHYP sends down the set state effecter call to Hard power off the host.
Previously, we werent checking if the customer APR policy is set to "AlwaysOff" and this broke the UPS usecase when after an AC loss, even though the customer set the IBM i OS value to stay off, as well as setting the Always Off setting in Power restore policy on ASMI. And they expect that if the system loses power, it will not automatically power on when power is restored.
Defect: 556277
TESTED: on rainier, setting the customer policy to "AlwaysOff" busctl get-property xyz.openbmc_project.Settings /xyz/openbmc_project/control/host0/power_restore_policy …
=> Check customer APR policy before setting one_time APR

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commits adds change to check for the customer PowerRestorePolicy before setting the one_time
PowerRestorePolicy when PHYP sends down the set state effecter call to Hard power off the host.
Previously, we werent checking if the customer APR policy is set to "AlwaysOff" and this broke the UPS usecase when after an AC loss, even though the customer set the IBM i OS value to stay off, as well as setting the Always Off setting in Power restore policy on ASMI. And they expect that if the system loses power, it will not automatically power on when power is restored.
Defect: 556277
TESTED: on rainier, setting the customer policy to "AlwaysOff" busctl get-property xyz.openbmc_project.Settings /xyz/openbmc_project/control/host0/power_restore_policy …
=> Check customer APR policy before setting one_time APR (#433)

meson_options.txt
To give more clarity, this commit adds an elaborate comment in meson_options explaining why 5 seconds DBUS timeout value was chosen for PLDM.
=> PLDM: Comment explaining dbus-timeout-value option

oem/ibm/libpldmresponder/file_io_type_pcie.cpp
```
As per current design, while displaying the topology data under GUI, bmcweb
looks for the fabric adapter location code to be the start of the IO Slot
Location codes(Fabric adapter and slots are in the same planar)
Example:
Fabric Adapter location code - U78CD.001.FZH1277-P1
IO Slot location code        - U78CD.001.FZH1277-P1-C3
But in case of splitter, the Slots are connected to the Midplane (Planar 3) and
not to the fabric adapter (P1 and P2).
Fabric Adapter location code - U50EE.001.WZS000P-P2-C1
IO Slot location code        - U50EE.001.WZS000P-P3-C10
To create a generic way to get the IO slots location codes in PCIeTopology,
creating association as shown below:
FabricAdapters -> PCIe Slots
The association between Fabric adapters and slots is created while parsing the
topology data. …
```
=> 1030: Association between fabric adapter and slots (#416)

oem/ibm/configurations/bios/string_attrs.json
Adding BIOS attribute to select OS load source
- Previously user had to do this configuration of selecting load
source, alternate load source and DASD load source manually,
and this was tedious task. These are network adapters connected
to PCI slots whose part location information is available in redfish.
- Adding bios attribute to handle selection of PCI slot location codes
for these network adapters to be selected from the GUI webpage, GUI
would then populate these BIOS attributes through redfish and this
selection will be communicated to Host via these PLDM BIOS attributes.
=> Adding BIOS attribute to select OS load source

common/bios_utils.hpp, common/test/pldm_utils_test.cpp, host-bmc/dbus_to_event_handler.cpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/bios_table.cpp, libpldmresponder/fru.cpp, libpldmresponder/pdr_utils.cpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp, libpldmresponder/platform_numeric_effecter.hpp, libpldmresponder/platform_state_effecter.hpp, libpldmresponder/platform_state_sensor.hpp, pldmd/pldmd.cpp, pldmtool/pldm_bios_cmd.cpp
Many of these changes are backports of patches already merged upstream, though have needed to be modified due to various downstream constraints.
With these patches I've booted a Rainier platform to host firmware standby without issue.
=> Migrate off of APIs deprecated in libpldm v0.4.0 

oem/ibm/libpldmresponder/file_io_type_lid.hpp
Commit the marker lid validate errors for the
min-mif level and access key expiration so that
it generates an SRC when we hit the error during
code update.
=> Throw Marker Lid validate error

libpldmresponder/fru.cpp, pldmtool/pldm_platform_cmd.cpp
Backport two patches from upstream openbmc/pldm that allow us to move forward to v0.6.0 of openbmc/libpldm
=> For/1060/libpldm v0.6.0

oem/ibm/libpldmresponder/inband_code_update.cpp
This commit adds change to move the fetching of activation property inside the inband code update path. As it is a no-op for out of band updates.
Defect: [565265](https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=565265)
=> Moving fetch activation property

oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json
According to the rainier workbook, the rainier1s-4u model has 16 nvme slots 8 in each disk_backplane0 and disk_backplane1.
The ibm,rainier1s-4u json had missing nvme slots entries and were not modelled by PLDM. This commit adds the same.
Fixes: 561341
Change-Id: I0559f1761a6ec223fa62aa14c283885d3aa37e49
=> pdr: Missing nvme slot entries in the json

oem/ibm/configurations/pdr/ibm,rainier-1s4u/11.json, oem/ibm/configurations/pdr/ibm,rainier-1s4u/4.json
The ibm,rainier1s-4u json had missing nvme slots and were not modelled by PLDM. This commit adds the same.
Fixes: 561341
Change-Id: I0559f1761a6ec223fa62aa14c283885d3aa37e49
=> pdr: Missing nvme slot entries in the json (#447)

oem/ibm/libpldmresponder/inband_code_update.cpp
This commit adds change to move the fetching of activation property inside the inband code update path. As it is a no-op for out of band updates.
=> Moving fetch activation property (#449)

common/utils.cpp, libpldmresponder/bios_config.cpp, oem/ibm/libpldmresponder/collect_slot_vpd.cpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_progress_src.cpp, oem/ibm/libpldmresponder/fru_oem_ibm.cpp, oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, softoff/main.cpp
This commit adds 5 second dbus timeout value to dbus calls with no reply. Previously a commit was merged that included 5 seconds dbus timeout value for all dbus call with reply.
This is added to make sure PLDM does not wait for more than 5 seconds when a dbus call is made with or without reply if no response is received from other daemon or host.
The 5 second  timeout value is overridden to 10 seconds in meta-ibm layer
=> PLDM: 5 sec timeout for dbus calls without reply

oem/ibm/configurations/pdr/ibm,bonnell/11.json, oem/ibm/configurations/pdr/ibm,bonnell/4.json
This commit adds missing led sensors/effecters in Bonnell system. As part of this, added different led objects for connectors, dimms, cpu, op-panel, TPM etc.
Tested By:
Powered on the system with the changes and verified that PHYP is receiving the newly added sensors and effecters. Identify operations are tested by changing it from Web GUI.
dimm-0 test:
Identify Sensor Off
pldmtool raw --data 0x80 0x02 0x21 0x23 0x00 0x01 0x00 pldmtool: Rx: 08 01 00 02 21 00 01 00 01 01 01
Fault Sensor Off
pldmtool raw --data 0x80 0x02 0x21 0x46 0x00 0x01 0x00 pldmtool: Rx: 08 01 00 02 21 00 01 00 01 01 01
Identify Effecter to On
pldmtool raw -d 0x80 0x02 0x39 0x27 0x00 0x01 0x01 0x02 pldmtool: Tx: 08 01 80 02 39 27 00 01 01 02
Fault Effecter to On
pldmtool raw -d 0x80 0x02 0x39 0x4A 0x00 0x01 0x01 0x02 …
=> oem-ibm: Add missing led sensors/effecters

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json, oem/ibm/configurations/bios/string_attrs.json
Adding bios attribute to configure network boot parameter from the GUI webpage, GUI would then populate these BIOS attributes through redfish and this selection will be communicated to pldm remote terminus via these PLDM BIOS attributes.
=> BIOS attribute to configure network parameter

oem/ibm/libpldmresponder/file_io_type_pel.cpp
When IBM's hypervisor receives an event log (PEL) using the file API, it may end up discarding it, returning the reason the file was discarded in the status argument of the file ack command.  It can do this for two reasons, either it doesn't have any more room to store event logs, or the event log was malformed.
In these cases, call the HostReject D-Bus method on the PEL daemon so it can handle it. The code must convert the value of the status returned into the proper D-Bus enum value.
Without this call, the operating system was missing event logs when there were floods of them.
Tested:
API was called when system was flooded with event logs, allowing the PEL daemon to resend them as space opens up.
Change-Id: I9d3acf4e5c5f885934ef96e89ddb93dd8f9c10a3
=> oem-ibm: Call PEL API when host drops event log

oem/ibm/libpldmresponder/inband_code_update.cpp
executeCmd() function is not getting used anywhere in the code.
Usage of executeCmd function was removed as part of inband code update changes.
Now its no longer used so removing it.
=> Removing the dead code

common/utils.cpp, host-bmc/dbus/serialize.cpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/fru.cpp, libpldmresponder/platform.cpp, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_vpd.cpp
As part of adding new features there were
traces that are still using standard ostream
pattern of logging. As PLDM repository migrated
to structured logging hence migrating the new
log traces to follow the same practice.
Additionally minor refinement of traces is also
handled as a part of this commit, listed below -
1. Correction in type of log (ex- error or info)
2. Correction in spelling of log message
3. Removing logs from test file.
=> PLDM: Implementing Phosphor-Logging/LG2 logging

common/utils.cpp, host-bmc/dbus/serialize.cpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/fru.cpp, libpldmresponder/platform.cpp, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_vpd.cpp
```
As part of adding new features there were
traces that are still using standard ostream
pattern of logging. As PLDM repository migrated
to structured logging hence migrating the new
log traces to follow the same practice.
Additionally minor refinement of traces is also
handled as a part of this commit, listed below -
1. Correction in type of log (ex- error or info)
2. Correction in spelling of log message
3. Removing logs from test file.
Signed-off-by: Riya Dixit <riyadixitagra@gmail.com>```
=> 1060: PLDM: LG2 migration for missed out traces (#466)

common/utils.cpp, common/utils.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp, libpldmresponder/platform_numeric_effecter.hpp
Added responder support for GetNumericEffecter Command
Test:
Using pldmtool raw command
pldmtool raw -d 0x80 0x02 0x32 0x23 00
pldmtool: Tx: 08 01 80 02 32 23 00
pldmtool: Rx: 08 01 00 02 32 00 00 01 03 03
=> Responder support for Get numeric effecter command

common/utils.cpp, common/utils.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp, libpldmresponder/platform_numeric_effecter.hpp
```
Added responder support for GetNumericEffecter Command
Test:
Using pldmtool raw command
pldmtool raw -d 0x80 0x02 0x32 0x23 00
pldmtool: Tx: 08 01 80 02 32 23 00
pldmtool: Rx: 08 01 00 02 32 00 00 01 03 03
Signed-off-by: Archana Kakani <archana.kakani@ibm.com>```
=> 1060: Responder support for GetNumericEffecterCommand (#470)

common/utils.hpp, oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/test/libpldmresponder_fileio_test.cpp, pldmd/pldm_resp_interface.hpp, pldmd/pldmd.cpp
- File transfer between BMC and Host is synchronous mechanism.
- File transfer interrupted because of many reasons, so if
file transfer interrupted between BMC and Host then PLDM is
ending up in the hung state and not able to respond to the
upcoming new requests. User has to do work around to restart
the PLDM to get work again.
- I have added asynchronous file transfer support using
eventloop mechanism and non-blocking socket communication,
so file transfer will be taken care by event loop and PLDM
is free to receive another request from the Host.
- If file transfer will be stuck or interrupted during
asynchronous transfer then time-out occurs and file transfer
will be aborted and same status communicated to the Host.
=> Adding response mechanism to remote terminus

pldmtool/pldm_platform_cmd.cpp
This commit provides support for the GetNumericEffecterValue command in pldmtool. This command takes the effecter id of the numeric effecter for which we need the value as input.
The OEM numeric effecter responder support for the getNumericEffecterValue is not implemented yet. Querying those effecters will respond with an error.
Tested:
pldmtool platform GetNumericEffecterValue -h
get the numeric effecter value
Usage: pldmtool platform GetNumericEffecterValue [OPTIONS]
Options:
-h,--help                   Print this help message and exit
-m,--mctp_eid UINT          MCTP endpoint ID
-v,--verbose
-i,--effecter_id UINT REQUIRED
A handle that is used to identify and access the effecter
Example:
pldmtool platform GetNumericEffecterValue -i 35
{
"effecterDataSize": 0, …
=> pldmtool: Support for Get Numeric Effecter Value command

oem/ibm/configurations/bios/enum_attrs.json, oem/ibm/configurations/bios/integer_attrs.json
This commit adds new BIOS attributes to support Linux KVM
=> OEM-IBM: BIOS attribute support for LINUX KVM

pldmtool/pldm_platform_cmd.cpp
```
This commit provides support for the GetNumericEffecterValue
command in pldmtool. This command takes the effecter id
of the numeric effecter for which we need the value as input.
The OEM numeric effecter responder support for the getNumericEffecterValue
is not implemented yet. Querying those effecters will respond with an error.
Tested:
pldmtool platform GetNumericEffecterValue -h
get the numeric effecter value
Usage: pldmtool platform GetNumericEffecterValue [OPTIONS]
Options:
-h,--help                   Print this help message and exit
-m,--mctp_eid UINT          MCTP endpoint ID
-v,--verbose
-i,--effecter_id UINT REQUIRED
A handle that is used to identify and access the effecter
Example:
pldmtool platform GetNumericEffecterValue -i 35
{
"effecterDataSize": 0, …
```
=> 1060: pldmtool: Support for Get Numeric Effecter Value command (#474)

host-bmc/dbus/chapdata.cpp, host-bmc/dbus/chapdata.hpp, host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/test/meson.build, libpldmresponder/meson.build, libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_type_chap.cpp, oem/ibm/libpldmresponder/file_io_type_chap.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/requester/dbus_to_file_handler.cpp, oem/ibm/requester/dbus_to_file_handler.hpp
- This commit will add two properties chapname and chapsecret to transfer encrypted password from GUI to Host via    pldm.
- When GUI modify these two properties then pldm will get the notification since pldm hosted these two properties and        pldm will transfer these data to remote terminus by FILEIO mechanism.
- Chapdata file will be created when dbus property chapsecret set via redfish interface and when chapdata transfer successful then output sample is below.
**Sample output:**
Nov 07 18:28:25 z2430cbmc pldmd[1066]: newFileAvailableSendToHost:Sending Sign CSR request to Host for  fileHandle: 0
Nov 07 18:28:25 z2430cbmc pldmd[1066]: Tx: 80 3f 0a 17 00 00 00 00 00 1c 00 00 00 00 00 00 00
Nov 07 18:28:25 z2430cbmc pldmd[1066]: Rx: 09 01 00 3f 0a 00
Nov 07 18:28:25 z2430cbmc …
=> pldm: Adding encrypted password transfer mechanism

oem/ibm/configurations/bios/enum_attrs.json
Introduce "Default" as an option for pvm_default_os_type BIOS attribute.
Tested by : IPL and power on/off tests
=> oem-ibm:Add default option for pvm_default_os_type

oem/ibm/configurations/fileTable.json
Add read-only lid 81e00670 which is a partition table that hostboot uses to get information about the other partition files.
Tested: Verified this lid was read by hostboot on a p10bmc system and that the system powered on.
Change-Id: If09ec0ae0938925f8a147dc28ea2d8b24f94c13d
=> oem: ibm: fileTable: Add lid 81e00670

oem/ibm/configurations/bios/enum_attrs.json
```
This change makes default OS type as "Default" instead of "AIX". Keeping default OS type as AIX can cause issues in systems where AIX is not installed. So the safer option is to keep default OS type as "Default" so PHYP can decide which OS has to boot. With Default, PHYP uses the RB keyword to boot to the default OS.
Tested By : Basic IPL testing and checked the default option on GUI.
Signed-off-by: vkaverap@in.ibm.com <vkaverap@in.ibm.com>
```
=> 1060: oem-ibm: Change default OS type from "AIX" to "Default"

oem/ibm/configurations/bios/enum_attrs.json
Modified the display name for Runtime Processor Diagnostic Guard Policy.
=> oem-ibm: Spelling correction Gard to Guard

oem/ibm/configurations/bios/enum_attrs.json
Change customer power policy mapping
This commit adds changes to change the mapping of "Disabled"
value from "None" to "AlwaysOff" for the BIOS attrubute
pvm_auto_poweron_restart, which is the BIOS attribute mapped
in the backend with the customer APR policy.
Change the mapping of "Disabled" value from "None" to "AlwaysOff" for the PLDM BIOS attrubute pvm_auto_poweron_restart, which is the BIOS attribute mapped in the backend with the customer APR policy. So that if the OS/PHYP sets the customer policy to "Disabled" the Dbus backend value for the customer policy will get changed to "AlwaysOff" instead of "None" as, if its "None" then when we check the customer policy before we set the one_time APR policy we do not see and "None" and see "AlwaysOff" instead.
Defect:588703
TESTED: tested by …
=> Change customer power policy mapping

oem/ibm/configurations/bios/enum_attrs.json
```
This commit adds changes to change the mapping of "Disabled"
value from "None" to "AlwaysOff" for the BIOS attrubute
pvm_auto_poweron_restart, which is the BIOS attribute mapped
in the backend with the customer APR policy.
Change the mapping of "Disabled" value from "None" to "AlwaysOff" for the PLDM BIOS attrubute pvm_auto_poweron_restart, which is the BIOS attribute mapped in the backend with the customer APR policy. So that if the OS/PHYP sets the customer policy to "Disabled" the Dbus backend value for the customer policy will get changed to "AlwaysOff" instead of "None" as, if its "None" then when we check the customer policy before we set the one_time APR policy we do not see and "None" and see "AlwaysOff" instead.
Defect:588703
TESTED: tested by powering on the IBMi system till …
```
=> 1020: Change customer power policy mapping (#492)

requester/handler.hpp, requester/test/handler_test.cpp
Section "Requirements for requesters" in DSP0240 details "A PLDM terminus that issues PLDM requests to another PLDM terminus shall wait until one of the following occurs before issuing a new PLDM request: it gets the response to a particular request, it times out waiting for the response, or it receives an indication that transmission of the particular request failed." So the registered request messages to one endpoint have to be queued before sending to meet the requester requirement.
When a sensor manager is added to pldmd daemon to manage the sensors of one terminus, the sensor manager will support the sensor polling timers. The timers will poll the PLDM sensors with different intervals so there can be many `getSensorReading` requests to one endpoint to get the sensor values. Moreover, …
=> requestHandler: Queue the request messages to one endpoint

oem/ibm/configurations/bios/ibm,bonnell/enum_attrs.json, oem/ibm/configurations/bios/ibm,everest/enum_attrs.json, oem/ibm/configurations/bios/ibm,rainier-1s4u/enum_attrs.json, oem/ibm/configurations/bios/ibm,rainier-2u/enum_attrs.json, oem/ibm/configurations/bios/ibm,rainier-4u/enum_attrs.json
Below are the two commits which were missed in System specific bios attributes changes.
1. Change customer power policy mapping (#496)
2. oem-ibm: Change default OS type from "AIX" to "Default" (#493) Rebasing those changes.
3. oem-ibm:Add default option for pvm_default_os_type (#484)
Tested:
Normal Poweron/off operation was successful.
=> pldm: Rebasing missed commits

oem/ibm/configurations/bios/ibm,bonnell/enum_attrs.json
Active memory mirroring is not supported in Bonnell. To remove that support
we are removing the bios attribute completely so that user will not have any access
to use the AMM setting.
Removed the bios attribute hb_memory_mirror_mode and hb_memory_mirror_mode_current
Fixes: 588132
Tested:
Poweron/poweroff and reset reload case, verified
/redfish/v1/Registries/BiosAttributeRegistry/BiosAttributeRegistry
=> oem-ibm: Disabling Active Memory Mirroring for Bonnell

oem/ibm/configurations/bios/ibm,everest/integer_attrs.json, oem/ibm/configurations/bios/ibm,rainier-1s4u/integer_attrs.json, oem/ibm/configurations/bios/ibm,rainier-2u/integer_attrs.json, oem/ibm/configurations/bios/ibm,rainier-4u/integer_attrs.json
This commit supports the Translation Control Entry (TCE) table preallocation for dynamic drawer add by introducing a new BIOS attribute of integer type that helps customers to control the number of additional slots that support dynamic external I/O drawer attach. That value is then communicated to the Hypervisor to control the amount
of TCE space that is pre-allocated during system power ON. The customer selects the number of additional slots from eBMC GUI.
Tested By: System power ON/OFF and checking the system specific values of BIOS attribute on respective systems
=> oem-ibm: TCE Table Preallocation for Dynamic Drawer Add

libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This commit implements building DIMM
PDRs and handles the DBus method call
with the dumpType as MemoryBufferSBE
and the failingUnitId as DIMM Id
based on effecter Id of numericEffecter
being set.
Test- Used pldmtool platform command
for setNumericEffecter which
triggered msbe dumpType.
=> pldm: SBE Dump Support for Odyssey

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/host_pdr_handler.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp
Added below changes to support multipath splitter
1. Add LinkReset to Logical slots
2. Fetch Logical slot entities from saved object paths.
3. Updated code to fetch the location code of logical slots too.
Tested:
1. Inventory LEDs page on GUI.
2. Identifying LEDs on Inventory Page works well.
3. Topology Page (Populates links properly)
4. Link Reset on few links
5. Verified Dbus details like Location code of Logical slots and Dbus Modelling of Topology data.
=> oem-ibm: Multipath Splitter support

host-bmc/utils.cpp
Find the Entity node in the entity association tree using is_remote as true
Host sends Splitter/mex PDRs during the PDR exchange. In case of splitter number of PDRs is more so there will be multiple respository changed events from Host. Splitter has 24 slots attached to it and CEC chassis has 12 slots. One of the repository change event is received for Slots to logical slots association in splitter.
While updating this association to the entity association tree, we search the node using the entity type and instance id, one of the CEC slot matches the requests and returns the CEC slot for the request of splitter slot node. and we end up creating logical slots under CEC motherboard.
To solve the issue we are using entity type, instance number and container id for entities for which has …
=> pldm: Fix for multipath splitter Dbus modelling of logical slots

host-bmc/dbus/serialize.cpp
System type is written to persist file during start up. Creating pldm folder under /var/lib before updating the system type to persist file.
PLDM was coredumping on manufacturing system as pldm folder did not exist in /var/lib while writting the system type to persist file.
Fixes: 597047
Tested:
Below steps:
1. Remove /var/lib/pldm
2. Restart pldmd
3. BMC reached ready state.
=> pldm: Creating /var/lib/pldm before updating system type

host-bmc/host_pdr_handler.cpp
Correct Dbus modelling of Led object when FRU is removed from pdr repository.
Currently, if PHYP deletes a FRU or sensors and effectors association with the FRU (from the PDR repository), in response to that BMC marks the state of the FRU to Absent. But leave the LocationIndicatorActive as how it was already there before removal (it can be either true/false/null based on how it was set previously ).
To modell hardware behaviour accurately when FRU or the Sensors/Effecters associated with FRU are removed from PDR repository, LED object are removed from PLDm Dbus tree.
Tested:
- Inject Nimitz FAN error
FAN becomes inaccessible and sensors/effecters are removed.
Dbus query does not show any LED object path associated with it
=> pldm: Remove led Dbus obj when FRU is removed from pdr repo

host-bmc/host_pdr_handler.cpp
```
Correct Dbus modelling of Led object when FRU is removed from
pdr repository.
Currently, if PHYP deletes a FRU or sensors and effectors
association with the FRU (from the PDR repository),
in response to that BMC marks the state of the FRU to Absent.
But leave the LocationIndicatorActive as how it was already
there before removal (it can be either true/false/null
based on how it was set previously ).
To modell hardware behaviour accurately when FRU or
the Sensors/Effecters associated with FRU are removed
from PDR repository, LED object are removed from PLDm Dbus tree.
Tested:
- Inject Nimitz FAN error
FAN becomes inaccessible and sensors/effecters are removed.
Dbus query does not show any LED object path associated with it
Signed-off-by: Archana Kakani <archana.kakani@ibm.com>```
=> 1020: pldm: Remove led Dbus obj when FRU is removed from pdr repo (#514)

host-bmc/host_pdr_handler.cpp
```
Correct Dbus modelling of Led object when FRU is removed from
pdr repository.
Currently, if PHYP deletes a FRU or sensors and effectors
association with the FRU (from the PDR repository),
in response to that BMC marks the state of the FRU to Absent.
But leave the LocationIndicatorActive as how it was already
there before removal (it can be either true/false/null
based on how it was set previously ).
To modell hardware behaviour accurately when FRU or
the Sensors/Effecters associated with FRU are removed
from PDR repository, LED object are removed from PLDm Dbus tree.
Tested:
- Inject Nimitz FAN error
FAN becomes inaccessible and sensors/effecters are removed.
Dbus query does not show any LED object path associated with it
Signed-off-by: Archana Kakani <archana.kakani@ibm.com>```
=> 1030: pldm: Remove led Dbus obj when FRU is removed from pdr repo (#514)

host-bmc/host_pdr_handler.cpp
```
Correct Dbus modelling of Led object when FRU is removed from
pdr repository.
Currently, if PHYP deletes a FRU or sensors and effectors
association with the FRU (from the PDR repository),
in response to that BMC marks the state of the FRU to Absent.
But leave the LocationIndicatorActive as how it was already
there before removal (it can be either true/false/null
based on how it was set previously ).
To modell hardware behaviour accurately when FRU or
the Sensors/Effecters associated with FRU are removed
from PDR repository, LED object are removed from PLDm Dbus tree.
Tested:
- Inject Nimitz FAN error
FAN becomes inaccessible and sensors/effecters are removed.
Dbus query does not show any LED object path associated with it
Signed-off-by: Archana Kakani <archana.kakani@ibm.com>```
=> 1050: pldm: Remove led Dbus obj when FRU is removed from pdr repo (#514)

libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp
This commit addresses some minor
issues discovered as part of integration
testing. Issues addressed:
- Invalid entity type
- Notification being sent to HB for all OCMB instead of the only one OCMB which is completing the dump. This is fixed for PROCs too.
=> pldm: SBE Dump Support for Odyssey fix

libpldmresponder/meson.build, oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_chap.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.cpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_smsmenu.cpp, oem/ibm/libpldmresponder/file_io_type_smsmenu.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/requester/dbus_to_file_handler.cpp, oem/ibm/requester/dbus_to_file_handler.hpp, oem/ibm/test/libpldmresponder_fileio_test.cpp, pldmd/pldmd.cpp
This supports the following password prompts for PFW (Platform Firmware) provided graphical SMS (System Management Services (SMS) menu
In system configurations that include a graphics adapter assigned to a partition, PFW can display the SMS menus on the console allowing users to interact with PFW using a keybaord. This menu requires as they can be used to change partition configurations (e.g. Boot option, I/O device info etc.)
Supported password prompt functions:
1. The ability to prompt for a username/password and provide authentication
2. The ability to change a password when the current password is expired
Tested:
1. Providing correct username and password for authentication sendFileAckWithMetaDataToHost fmd1=0 fmd2=1 fmd3=4294967295 fmd4=4294967295 Tx: 80 3f 0f 18 00 01 00 01 00 00 00 …
=> pldm: Support password prompt for graphical SMS menu

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_chap.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_smsmenu.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp
When HOST read/write data to BMC using DMA then BMC checks the length of the data to be read/write and devide into chunks if data length is more than DMA max size.
This change will fix the issue in PLDM when it send data transfer status to the HOST and sending left over length as response which is wrong and now PLDM sends correct response with length.
_Defect_: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=612662
Tested:
IPL flow tested and PHYP reaches till standby which include all type of file transfer from BMC to PHYP.
=> oem-ibm: Fixing DMA length issue

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp
```
When HOST read/write data to BMC using DMA then BMC checks the length
of the data to be read/write and divide into chunks if data length is
more than DMA max size.
This change will fix the issue in PLDM when it send data transfer
status to the HOST and sending left over length as response which is
wrong and now PLDM sends correct response with length.
```
=> 1030: Fixing Read lid size corruption issue (#525)

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp
```
When HOST read/write data to BMC using DMA then BMC checks the length
of the data to be read/write and divide into chunks if data length is
more than DMA max size.
This change will fix the issue in PLDM when it send data transfer
status to the HOST and sending left over length as response which is
wrong and now PLDM sends correct response with length.
```
=> 1050: Fixing Read lid size corruption issue (#525)

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp
```
When HOST read/write data to BMC using DMA then BMC checks the length
of the data to be read/write and divide into chunks if data length is
more than DMA max size.
This change will fix the issue in PLDM when it send data transfer
status to the HOST and sending left over length as response which is
wrong and now PLDM sends correct response with length.
```
=> 1110: Fixing Read lid size corruption issue (#525)

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp
```
When HOST read/write data to BMC using DMA then BMC checks the length
of the data to be read/write and divide into chunks if data length is
more than DMA max size.
This change will fix the issue in PLDM when it send data transfer
status to the HOST and sending left over length as response which is
wrong and now PLDM sends correct response with length.
```
=> 1020: Fixing Read lid size corruption issue (#525)

host-bmc/dbus_to_host_effecters.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commit updates the severity of PEL
'xyz.openbmc_project.PLDM.Error.SetHostEffecterFailed' from ERROR to INFORMATIONAL.
Test: Triggered set numericEffecter at runtime and verified the severity of PEL logged as INFORMATIONAL.
=> host-bmc: Update set host effecter PEL severity

host-bmc/dbus_to_host_effecters.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
```
This commit updates the severity of PEL
'xyz.openbmc_project.PLDM.Error.SetHostEffecterFailed' from ERROR to
INFORMATIONAL.
Test: Triggered set numericEffecter at runtime and verified the severity of PEL logged as INFORMATIONAL.
Signed-off-by: Riya Dixit <riyadixitagra@gmail.com>```
=> 1030: host-bmc: Update set host effecter PEL severity (#534)

common/utils.hpp, oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/test/libpldmresponder_fileio_test.cpp, pldmd/pldm_resp_interface.hpp, pldmd/pldmd.cpp
The transfer files between BMC and Remote terminus as synchronous
manner. Previously if file transfer was interrupted between BMC and
Remote terminus then PLDM is ending up in the hung state and not able
to respond to the incoming new requests. User has to do work around to
restart the PLDM to work again.
This commits adds support for asynchronous file transfer using
eventloop mechanism and non-blocking socket communication, so file
transfer will be taken care by event loop and PLDM is free to receive
another request from the Remote terminus. In case file transfer will be
stuck or interrupted during asynchronous transfer then time-out occurs
and file transfer will be aborted and same status communicated to the
Remote terminus.
=> Adding support for asynchronous file transfer

host-bmc/custom_dbus.cpp, host-bmc/custom_dbus.hpp, libpldmresponder/meson.build, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/requester/dbus_to_file_handler.cpp, oem/ibm/requester/dbus_to_file_handler.hpp, pldmd/pldmd.cpp
This commit supports:
1. Creation or update of new license interfaces and properties supplied by host
2. Clearing of license status to Unknown, during host power off transition
3. Restoration of license interfaces during reset reload and setting the license status to Unknown
Tested By:
1. Verified that dbus hosting is done by pldm
2. CoD(Capacity on demand) values are coming up in the BMC
3. Verified that reboot of BMC does not clear values
Change-Id: I23e7e6a533ef869329abe555790b584430f3f8c4
=> oem-ibm: Capacity on demand licensing support

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Bonnell/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/enum_attrs.json, oem/ibm/configurations/bios/enum_attrs.json
This commit adds value_name json key to BIOS attribute that allows user to enable/disable the dynamic deallocation of memory based on predictive memory fail events.
Tested: Verified the BIOS attribute with get bios attribute command from pldmtool.
=> oem-ibm: Adding value_name json key for dynamic deallocation of Memory

host-bmc/host_pdr_handler.cpp, libpldmresponder/platform.cpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/requester/dbus_to_file_handler.cpp
In the pel registry , we have already removed all the instances where we send InternalError error, since its not really useful for debugging.
We need to carefully check the cases and add unique errors in the pel registry and then add those to the pldm code. Removing them for now to unblock the driver release.
=> Remove all instances where we log InternalError

libpldmresponder/platform_config.cpp, libpldmresponder/platform_config.hpp, pldmd/pldmd.cpp
This commit adds support to find the system type by checking the JSON
directory presence when entity manager sends the system names. Once
system type is set then PLDM continues the further operations like pdr
generation, system specific bios etc...
Testing:
Tested on real two types of hardware everest/raininer
=> pldm: New system type support

oem/ibm/libpldmresponder/file_io.cpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/utils.hpp
When user do chasisoff then power is abruptly down for chassis and NVRAM file transfer is abruptly stops which leads to mismatch NVRAM file checksum and PHYP updated checksum due to data corruption. This commit adds the synchronous file transfer mechanism only for NVRAM and Checksum file to avoid race condition while chassis off.
=> pldm: Adding Fix for NVRAM checksum corruption

libpldmresponder/platform.hpp, libpldmresponder/test/libpldmresponder_pdr_effecter_test.cpp, libpldmresponder/test/libpldmresponder_pdr_sensor_test.cpp, libpldmresponder/test/libpldmresponder_platform_test.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp, pldmd/pldmd.cpp, pldmtool/oem/ibm/oem_ibm_state_set.hpp, pldmtool/pldm_platform_cmd.cpp
This commit adds a single OEM state effecter with a OEM entity type and with states [7, 9, 10] to perform 3 custom actions ReIPL, PowerDown and ArmAPR.
The defined states are
PLDM_POWER_CYCLE_OFF_SOFT_GRACEFUL= 7,
PLDM_POWER_OFF_SOFT_GRACEFUL= 9 and
PLDM_POWER_OFF_HARD_GRACEFUL= 10
When PHYP toggles the PLDM_POWER_CYCLE_OFF_SOFT_GRACEFUL we set the state manager property RequestedHostTransition to ForceWarmReboot instead of Reboot, this will directly reboot the host firmware without notification and chassis power will remain on throughout the reboot, instead of doing a graceful reboot.
=> oem-ibm: PLDM Power down effecter and APR support

configurations/pdr/com.ibm.Hardware.Chassis.Model.Bonnell/4.json, configurations/pdr/com.ibm.Hardware.Chassis.Model.Everest/4.json, configurations/pdr/com.ibm.Hardware.Chassis.Model.Rainier1S4U/4.json, configurations/pdr/com.ibm.Hardware.Chassis.Model.Rainier2U/4.json, configurations/pdr/com.ibm.Hardware.Chassis.Model.Rainier4U/4.json, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp, pldmtool/oem/ibm/oem_ibm_state_set.hpp
Real SAI(Sysytem Attention Indicator) is a physical led indicatori which lights up whenever there is a platform error (originated from BMC) or a partition error that is not mapped to any physical FRU (Field Replaceable Unit)
Real SAI scenarios
1. Real SAI effecter can be turned off by the user OR by host
2. Real SAI sensor is turned on if any of the partition SAI Or platform SAI is turned on
3. Real SAI is turned off if both partition and platform SAI are turned off
4. SAI data should be synced to host when host is up
Testing Data:
Real SAI Effecter:
{
"nextRecordHandle": 87,
"responseCount": 30,
"recordHandle": 86,
"PDRType": "State Effecter PDR",
"dataLength": 16,
"effecterID": 5,
"entityType": "[Physical] OEM IBM …
=> oem-ibm: Add Real SAI sensor and effecter PDR support

host-bmc/host_pdr_handler.cpp
This commit logs PEL when BMC fails to collect PDR from host.  GetPDR returns no response because of BMC PDR exchange failure after three tries get exhausted and timeout occurs.
Tested: Functional testing.
=> host-bmc: Logging PEL for PDR Exchange Failure

oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/requester/dbus_to_file_handler.cpp, oem/ibm/requester/dbus_to_file_handler.hpp
The dump entries are numbered in a new format (for ex:
System dump entry is numbered - A000<>
Resource dump entry is numbered - B000<>)
Made changes in code to incorporate these changes.
The code also changes the Token handling and UserChallenge
changes in 1110.
tested: Token and dump flow was successfully tested.
Change-Id: I0a7ddc71af87224d79ba7576b3c94fa8b25e2085
=> oem-ibm: Changes to handle the new way of Dump entry

host-bmc/utils.cpp
This commit add support to check if Dbus interface are hosted by other application or not.
if Dbus interface hosted by othe app then PLDM will skip the hosting and take existing path.
Tested:
Tested motherboard interface which is hosted by inventory manager:
` DICT_ENTRY "sas" {
STRING "xyz.openbmc_project.Inventory.Manager";
ARRAY "s" {
STRING "xyz.openbmc_project.Inventory.Decorator.LocationCode";
STRING "xyz.openbmc_project.Inventory.Item";
STRING "**xyz.openbmc_project.Inventory.Item.Board.Motherboard**";
STRING "xyz.openbmc_project.Object.Enable";
STRING "xyz.openbmc_project.State.Decorator.OperationalStatus";
};
};
DICT_ENTRY "sas" {
STRING "xyz.openbmc_project.PLDM";
ARRAY "s" {
STRING "org.freedesktop.DBus.Introspectable";
STRING "org.freedesktop.DBus.Peer";
STRING …
=> pldm: Adding exception handling while hosting Dbus path

softoff/main.cpp
This commit adds back PEL SRC to create while logging host poweroff timeout while rebasing in 1110.
Defect 638017
=> softoff: Add back missing PEL SRC

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
When there is a PDR exchange happening with host and we trigger a poweroff we were logging a pel BD8D6026 when the PDR exchange fails. This change is needed check if the host is up or not and then log an error if host is up.
=> pdr: Avoid logging PEL when host is transitioning to off

pldmd/pldmd.cpp
The oemUtilsHandler was declared in oem-ibm scope and accessed outside oem-ibm scope which would cause a problem when pldm was compiled with oem-ibm disabled.
=> Move the oemUtilsHandler declaration out of oem-ibm

oem/ibm/libpldmresponder/fru_oem_ibm.cpp, oem/ibm/libpldmresponder/utils.cpp
This commit fixes the issue of UAK date disaplay in the ASMI GUI when installed with changed UAK license with new date.
Tested: Verified that applying the the new UAK license value at power on state is being reflected in the ASM GUI
=> oem-ibm: Fix for UAK dbus update

host-bmc/host_pdr_handler.cpp, libpldmresponder/platform.cpp
The PDR exchange intermittently fails with "waiting for BMC Repo Change Event" and HB TIs waiting for the signal.
=> pdr: Fixes few issues

oem/ibm/configurations/fileTable.json
Add 2 new lids and update the permissions for hostboot's DEVTREE to be read-write.
Change-Id: I95006e2b37d15a148f072f66804950e983ea1aab
=> oem: ibm: fileTable: Add new lids and update permissions

oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/inband_code_update.cpp
1. Moving fetch activation property (#449)
This commit adds change to move the fetching of activation
property inside the inband code update path. As it is a no-op
for out of band updates.
2. Throw Marker Lid validate error (#446)
Commit the marker lid validate errors for the
min-mif level and access key expiration so that
it generates an SRC when we hit the error during
code update.
3. Return proper Success/Error code to host (#442)
This commit adds change to send the right error code
to host during the marker lid validation. When the marker
lid validation fails we were trying to send a PLDM_ERROR
But it was sent as a response to the file write request
and PHYP assumed that the error code returned was for the
write operation and did not go ahead to check the sensor
event sent to indicate …
=> 1110 marker lid

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Bonnell/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/enum_attrs.json
When a predictive memory fail event occurs, the system dynamically deallocates an entire memory interleave group that includes the failing memory module. This commit adds BIOS attribute for allowing user to enable/disable the dynamic deallocation of memory based on predictive memory fail events.
Tested: Verified the BIOS attribute with get bios attribute command from pldmtool.
=> oem-ibm: Adding BIOS attribute for dynamic deallocation of Memory

oem/ibm/libpldmresponder/fru_oem_ibm.cpp
The PCIe Config data is a 64 bytes huge data which needs to be parsed and corresponding DBus values needs to be updated. The parsing logic had a pointer increment issue that resulted in some bug w.r.t the values.
Removed a debug trace as it is not having much value.
tested on a rainier and blueridge systems.
=> oem-ibm: Fix in pointer increment in the PCIe Config Data

oem/ibm/libpldmresponder/file_io_by_type.cpp
During File IO operation 3 bytes are getting added extra while responding to host.
minimum command size is 5 bytes but as per new change uint8_t size which is 8 is getting added which cause the issue while responding to PHYP.
=> Removing extra bytes while responding host

oem/ibm/libpldmresponder/file_io_by_type.cpp, oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_cert.cpp, oem/ibm/libpldmresponder/file_io_type_cert.hpp, oem/ibm/libpldmresponder/file_io_type_chap.hpp, oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/file_io_type_dump.hpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/file_io_type_lic.hpp, oem/ibm/libpldmresponder/file_io_type_lid.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/file_io_type_pel.cpp, oem/ibm/libpldmresponder/file_io_type_pel.hpp, oem/ibm/libpldmresponder/file_io_type_progress_src.hpp, oem/ibm/libpldmresponder/file_io_type_vpd.hpp
there is a race condition occurs between performing post operation and
sending response to Host. When host sends pels then bmc takes some time
to store the pels and meanwhile host is timed-out so it will try again
to transfer the pels and suddenly BMC finishing the storing and sending
failure status to host which causing the problem.
=> Fixing race condition during file transfer

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp
When there is a PDR exchange happening with host and we trigger a poweroff we were logging a pel BD8D6026 when the PDR exchange fails. This change is needed check if the host is up or not and then log an error only if host is up.
=> pdr: Log a PEL only when Host is Running

oem/ibm/libpldmresponder/file_io_by_type.cpp
The code lines for hardware and hostboot dumps which gets the handler for the dumps was commented which caused an error when we try to offload the HB and HW dumps to PHYP in a non-HMC managed systems.
Tested: Succesfully offloaded the hardware and hostboot dump to PHYP
Change-Id: I9d89b01c1a36af0a1487d814fd0564b61af5ab02
=> oem-ibm: Fix a minor bug in dump offload path

.secrets.baseline, common/utils.cpp, fw-update/device_updater.hpp, fw-update/inventory_manager.hpp, fw-update/package_parser.hpp, fw-update/update_manager.hpp, host-bmc/dbus/associations.hpp, host-bmc/dbus_to_event_handler.cpp, host-bmc/dbus_to_host_effecters.hpp, host-bmc/host_condition.hpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/base.hpp, libpldmresponder/bios_attribute.cpp, libpldmresponder/bios_config.cpp, libpldmresponder/fru.hpp, libpldmresponder/platform.hpp, oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/requester/dbus_to_file_handler.cpp, pldmd/dbus_impl_pdr.hpp, pldmd/dbus_impl_requester.hpp, pldmd/pldm_resp_interface.hpp, pldmtool/pldm_base_cmd.cpp, pldmtool/pldm_cmd_helper.hpp, pldmtool/pldm_platform_cmd.cpp, requester/handler.hpp, requester/mctp_endpoint_discovery.cpp, requester/request.hpp, softoff/softoff.cpp
Due to new change in openbmc-build-scripts for the 1110 branch to clang-18, a lot of files were failing in CI format. Adding the changed format files in correspondance to CI update.
=> CI: Adding format change

oem/ibm/libpldmresponder/file_io_by_type.hpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp
As part of libpldm master commit [1] symbolic link of file_io.h is removed, so changing the include path of file_io.h.
[1]: https://github.com/ibm-openbmc/libpldm/pull/41/commits/a1efaa2ef3811d900e1c4ab5b5af1933a6286241
=> Changing libpldm file_io.h file path

host-bmc/host_pdr_handler.cpp, libpldmresponder/oem_handler.hpp, libpldmresponder/platform.cpp, libpldmresponder/platform.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp, requester/request.hpp
This commit adds support for building Platform Dump Records (PDRs) related to DIMM and PROC entities. It handles DBus method calls for the respective dump types associated with each entity type. Additionally, it monitors dump progress status and triggers a request to set the host effecter.
Test- Used pldmtool platform command for setNumericEffecter.
=> oem-ibm: Implement SBE dump support

libpldmresponder/platform.cpp
This commit adds a minor fix to isOemStateEffecter missed out in SBE Dump implement rebase due to which pldm was getting hung as code control was getting stuck in the while loop of pdrRecord check due to the missing else condition in the loop.
Tested: Did persistent patch testing with setNumericEffecter cmd, did poweron of the persistent patch, flashed a complete openbmc image and did poweron till PHYP runtime. Also did boot side switch and poweron the driver to boot till PHYP runtime.
=> libpldmresponder: Minor fix in isOemStateEffecter

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Bonnell/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/enum_attrs.json
This commit enhances the displayName and helpText of hb_predictive_mem_guard and hb_predictive_mem_guard_current bios enum attribute.
=> oem-ibm: Change in hb_predictive_mem_guard bios attribute

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commit adds a fix to update container id by passing range of HB record handles to pldm_find_container_id api so as to search container id from BMC pdr and not HB pdr.
Tested: Tested: Verified numeric effecter pdrs with entity association pdrs and state effecter pdrs to have same container id for a particular entity as populated in entity association BMC pdrs after normalization post PDR exchange [1].
[1]:
https://gist.github.com/riyadixitagra/1a06a9ba32944193066a2d24efd66385
=> oem-ibm: Fix in updating container IDs

oem/ibm/libpldmresponder/fru_oem_ibm.cpp
This commit adds the dbus timeout while setting the changed firmware UAK value.
Tested:
Verified that UAK update is getting reflected in the corresponding UTIL D8 VPD keyword and the redfish
=> oem-ibm: Add the dbus timeout while setting UAK

common/utils.cpp, host-bmc/host_pdr_handler.cpp, libpldmresponder/bios_config.cpp, oem/ibm/libpldmresponder/inband_code_update.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/platform_oem_ibm.cpp
Added missed code and traces from 1060 in code update path.
The problem faced during existing code update code is the delay in receiving the system type. PLDM was setting the fw_boot_side and fw_boot_side_current before building the bios table. So those values where not getting set.
To fix the issue saving the pending bios attributes before setting biostable and resetting it after biostable update.
With the Fix pldm is booting from Temp side after codeupdate.
=> codeupdate: Fix to boot always from temp side

libpldmresponder/platform.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, pldmtool/oem/ibm/oem_ibm_state_set.hpp
This commit introduces new oem sensor PDRs of state set id - PLDM_OEM_IBM_SBE_DUMP_UPDATE_STATE(32777) whose state will be set for ocmb dump progress status. This change implements the new sensor based dump design only for ocmb sbe dumps whereas the sbe PROC dump design remains unchanged. As part of this change PLDM will be updating the sensor state with dump progress state. The remote terminus will be using polling mechanism on getStateSensorReadings command for dump status update.
Tested: Used pldmtool to set numeric effecter for triggering dump.
=> oem-ibm: Introducing sensor design for SBE ocmb dump

libpldmresponder/bios_config.cpp, oem/ibm/libpldmresponder/file_io_type_lic.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/utils.cpp
This commit handles the CoD license json parsing exception by correctly catching it and returs the error to the caller. Also made the change to avoid the removal of license json file whenever shared by the host.
Tested:
Done the sanity testing to verify that json file was kept without removal.
=> oem-ibm: Handle the json parse exception correctly

oem/ibm/configurations/pdr/ibm,bonnell/11.json
Add the entries to Bonnell's 11.json so that the host can send down the PCIE slot power states for the four PCIe slots.  These are the same as on Rainier and Everest.
Tested:
The power state in phosphor-inventory-manager is accurately reflected for a plugged in card.
Change-Id: Ic04e6d11750add7656bc7ac40135e2bfa4b8490e
=> configs: Add PCIe slot power states for Bonnell

oem/ibm/libpldmresponder/file_io_type_dump.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
This commit corrects the error log name according to the latest PEL message registry values.
Tested:
Restart of the pldm daemon does not cause any new error logs.
=> oem-ibm: Error log name correction

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Bonnell/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/enum_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/enum_attrs.json
Updated the Power supply attribute name from hb_power_PS*_functional to hb_power_PS*_present to match the upstream.
The upstream for this change is
https://gerrit.openbmc.org/c/openbmc/pldm/+/61015
=> bios: Updated Power supply bios attribute name

oem/ibm/libpldmresponder/file_io_type_dump.cpp
This commit fixes the issue where the BMC dump or the checkstop dump generated in a non-hmc managed system is not getting offloaded to the Operating System.
Fixes: EWM 643345
Tested By:
Verified that BMC dump and checkstop dump are getting offloaded successfully from BMC.
=> oem-ibm: Fix for dump offload issue

libpldmresponder/fru.cpp, oem/ibm/libpldmresponder/utils.cpp
Removing the check for IBM cable card because this will be verified in VPD and there is no need to have an additional check inside PLDM
Tested by : performing CM on IBM cable cards and industry standard adapters
=> Remove check for IBM cable card

libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp
This commit fixes the issue of calculating the processor core count incorrectly.
Fixes: STG Defect 658536
Tested By:
Tested the changes in a Blue ridge system and verified that, the processor core count is coming up correctly under each of the processors.
=> pldm: Fix the incorrect processor core count

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp
Change LanesInUse to type size_t from int64_t. This change is made as per upstream changes at [1]
[1]: https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/53650
=> Change LanesInUse type to size_t

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Bonnell/string_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/string_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/string_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/string_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/string_attrs.json, oem/ibm/configurations/bios/string_attrs.json
This commit introduces two new string bios attributes to capture system code level version with which last CEC full IPL was performed and another attribute to capture version level in case of MPIPL (after concurrent code update) scenario. Both the attributes will be updated by remote terminus during every IPL.
Tested: Verified with a BMC poweron
=> oem-ibm: Adding BIOS attribute for IPL version

oem/ibm/configurations/fileTable.json
Add the following 1060 commits to 1030, except the lids for Bonnell:
- https://github.com/ibm-openbmc/pldm/commit/939400b2f91a036582e052bb00fd9557d3f1c1f6
- https://github.com/ibm-openbmc/pldm/commit/4971dcff3b810e1048a97d7bca016112f9b6d805
Verified that all the lids in the hostfw json file for 1030 are now listed in the pldm table.
=> 1030: oem: ibm: fileTable: Add lid files for P10

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/pcie_topology.cpp, host-bmc/dbus/pcie_topology.hpp, host-bmc/test/meson.build, libpldmresponder/meson.build, oem/ibm/libpldmresponder/file_io_type_pcie.cpp, oem/ibm/libpldmresponder/file_io_type_pcie.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp, pldmd/pldmd.cpp
This commit adds support to implement the topology interface and also host it under PLDM and also supports the set and get property under the topology interface.
When PCIeTopologyRefresh property is set to true, we send the setEffecterCall to host to set the effecter state 1 and 2. When SaveTopologyRefresh property is set to true we send the setEffecterCall to host to set the effecter state to 3 and then sets it back to false.
Tested the 2 properties and worked fine
Change-Id: Ic53f6fd33bbc4a84136b3f70517ee5cb4d8488a3
=> oem: ibm: PCIe Topology support

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/linkreset.cpp, host-bmc/dbus/linkreset.hpp, host-bmc/host_pdr_handler.cpp, host-bmc/test/meson.build, libpldmresponder/meson.build, oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/libpldmresponder/oem_ibm_handler.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp
This commit implements the link reset feature. When the link reset property is set to true, a host state effecter is triggered following which the link reset property is set back to false again.
Tested: Using busctl command
=> oem-ibm : PCIE linkreset support

libpldmresponder/fru.cpp, oem/ibm/libpldmresponder/utils.cpp
There is multiple issues faced during the CM. This commit fixes below issues
1. Port PDRs not getting generated after adding cable card concurrently
2. Multiple adapter were seen under single I/O Slot
3. No adapter PDRs for the cards under NVMe Slots (Drive Backplane)
When resolving issues, the design is that the Adapter PDR will always remain in the PDR repository, regardless of whether the card is physically present or absent.
Tested:
Using busctl commands
=> libresponder: Fixing issues in CM path

oem/ibm/libpldmresponder/oem_ibm_handler.cpp, oem/ibm/test/libpldmresponder_oem_platform_test.cpp
Earlier, we were using the getSubTree API, which returns a pair of object paths and a mapper service map. From this, we extracted the object path and stored it for future retrieval of the entity ID from that path. We are now replacing this API with the existing getSubTreePaths API, as it returns only the object paths, which we use to extract entity IDs. Additionally, the function to extract the entity IDs now utilizes regex for a more dynamic approach instead of using hardcoded character position indices to extract the entity ID.
Tested: Verified the PDRs for populating correct entity instance IDs.
=> oem-ibm: Improving SBE Dump

oem/ibm/libpldmresponder/oem_ibm_handler.cpp
The dbus calls in PLDM was overridden by a dbusTimeOut option. The commit adds the missing overridden timeOuts in dbus method calls.
Change-Id: I6f41e7606d14c04786aca6e700a7d1dff697011e
=> oem-ibm: Add the missing DBus Timeouts

libpldmresponder/fru.cpp, libpldmresponder/oem_handler.hpp, oem/ibm/libpldmresponder/fru_oem_ibm.cpp, oem/ibm/libpldmresponder/fru_oem_ibm.hpp, oem/ibm/libpldmresponder/utils.cpp, oem/ibm/libpldmresponder/utils.hpp, pldmd/oem_ibm.hpp, pldmd/pldmd.cpp
The CheckIfIBMFru function is defined in OEM path and should only be invoked when oem_ibm is enabled.
Adding this fix to solve the huygen's build error
=> Call CheckIfIBMFru only when OEM_IBM is enabled

requester/handler.hpp
The queue logic of queuing the requests to a endpoint was removed/reverted in 1110. There was a extra check that was added as part of it to check duplicate key when we call registerRequest.
This check is removed in this commit.
Change-Id: I721b5d287ac657c9c7709b9530d09323af842dba
=> requester: Remove the extra check

oem/ibm/libpldmresponder/fru_oem_ibm.cpp
While processing the OEM FRU records, the datasize was not updated correctly causing PLDM to set the UAK value multiple times.
Tested:
UAK and PCIeConfig Data updated correctly after poweron.
=> oem: Fix UAK issue

host-bmc/dbus/custom_dbus.cpp, host-bmc/dbus/custom_dbus.hpp, host-bmc/dbus/deserialize.cpp, host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, host-bmc/utils.cpp, host-bmc/utils.hpp, oem/ibm/libpldmresponder/file_io_type_pcie.cpp
This commit supports the addition of IBM OEM FRU Names. Pretty name of the inventory item is updated by extracting the Entity Auxiliary Names PDR passed from host.
Tested By:
Verified that the decode of Entity Auxiliary Names PDR results in the intended pretty name string.
=> pldm: LI 1TM IBM OEM FRU Names Support

meson.options
Between releases 1020 and 1060, we successfully relied on the default PLDM timeouts for requests originating from the BMC.
However, starting with the 1110 drivers, we began encountering intermittent issues where the BMC was under heavy load due to CPU-intensive applications. As a result, PLDM often received limited CPU cycles during reset and reload operations. This meant that even though PHYP responded within the expected timeout window, PLDM was unable to process the requests in time.
To address this, this commit updates the response timeout to **5 seconds** and the instance ID expiry timeout to **12 seconds**.
=> Introduce New Response and Instance Expiry Timeouts

host-bmc/host_pdr_handler.cpp
The PCIeDevice was associated with multiple PCIeSlots due to the error when creating the association between devices and slots. The commit fixes the association issues present.
Tested: Checked the associations and the topology page loaded fine.
Change-Id: I782f8b8b9f31ea2a8bd9ab68cbfd168eed01602f
=> topology: Fix to solve multiple associations

oem/ibm/libpldmresponder/utils.cpp
Adding a presence check of the fru before populating the topology information.
If the JBOF card is replaced by cable card in the slot, the Dbus inventory under the PCIe card contain all the connectors underneath JBOF card as well as cable card and "Present" property provides the information about which connectors are active at the moment. PLDM need to check "Present" property to fetch the right object path to create the proper association.
=>  oem: Check presence of the fru before populating topology information

oem/ibm/libpldmresponder/utils.cpp
Topology information contains GenerationsInUse and LanesInUse details which are populated under PCIeDevice interface. ObjectPaths are created for all the adapters present/absent. Topology data is expected to be populated for all the adapters regardless of their presence.
=> oem: Verify connector presence before creating cable associations for topology

oem/ibm/libpldmresponder/utils.cpp
Topology information contains GenerationsInUse and LanesInUse details which are populated under PCIeDevice interface. ObjectPaths are created for all the adapters present/absent.
Topology data is expected to be populated for all the adapters regardless of their presence.
=> oem: Verify connector presence for cable association in topology

oem/ibm/libpldmresponder/file_io_type_dump.cpp
When a resource dump is created with an empty resource selector from GUI, a system dump is generated and this was entering our resource dump path and was creating wrong entry name.
This is seen in 1110 because of the recent changes in the naming format of the dumps.
Resource dump starts with 'B' and System dump starts with 'A'.
Tested with the fix and it worked good.
Change-Id: Iac7d1455f568e928132c80abb562978184109294
=> oem-ibm: Fixes the issue in resource dump entry

oem/ibm/libpldmresponder/file_io_type_pel.cpp
```
The storePel function used call_noreply, a synchronous D-Bus method
with timeout of 5 secs, which caused it to timeout in some scenarios.
To mitigate this issue, it has been replaced with call_async method.
Additionally, PLDM_SUCCESS is being returned now regardless of
the method call outcome. In case of any error during the async
method call, it will be logged by the callback function.
Change-Id: Ifbb80585ace516c8d4bf484c08356c3734d351fc
Signed-off-by: Jino Abraham <jinoabraham26@gmail.com>
```
=> 1050: libpldmresponder: Use async call in storePel (#675)

oem/ibm/libpldmresponder/file_io.hpp
Earlier dump manager was not creating a system dump entry when a disruptive system dump was triggered. Recent changes in dump manager started creating a dump entry and we had to handle the scenario when the SystemImpact was Disruptive. When it is a disruptive system dump we must ignore and do not process it.
Change-Id: I5afb3d4ee1e9f20afbe264ba613073b11faf6199
=> oem-ibm: Handle the Disruptive System Dump

oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Everest/bios_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier1S4U/bios_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier2U/bios_attrs.json, oem/ibm/configurations/bios/com.ibm.Hardware.Chassis.Model.Rainier4U/bios_attrs.json
This commit contains below changes
1. Update the updates in Everest/Fuji configuration
2. Removes the attribute from Rainier/Blu ridge systems
Tested By:
Verified that changes got reflected in BMC GUI. System power on operation worked good
Change-Id: Id321650b04b9ea2c47f8fe7a8550d1b0b863f048
=> oem-ibm: Dynamic I/O drawer attachment updata

oem/ibm/libpldmresponder/file_io.hpp, oem/ibm/libpldmresponder/utils.cpp
We are facing issues with dump offload where PLDM is timing out while waiting for connection from BMCWeb on unix socket which is used to transfer dump data.
Increased select timeout to 2sec to solve the dump download failure.
Fixes: STG Defect 690577
=> oem-ibm: Increased wait for connection during dump offload

libpldmresponder/platform.cpp
Added support to fetch record handles from the repository change request for the Records Deleted Event.
Fixes: STG Defect 692402
=> libresponder: Get record handles from RepoChangeEvent

softoff/softoff.cpp
SoftOff fails to find the host effector pdr in BMC PDR repository if the softoff request arrives in the time window where HB is down and PHYP is up but PDR exchange with PHYP is not completed.
Fixed: STG Defect 689447
=> soft-off: Return error if effecterid is not found

meson.options
This reverts commit 3ade053d0e3d72f209c9832829d1b77143e29ee5.
There are cases where we have seen that instance id's are exhausted, having less instance id expiry timeout would help recover the instance ids faster.
=> Revert "Introduce New Response and Instance Expiry Timeouts (#661)"

host-bmc/dbus/linkreset.cpp, pldmd/pldmd.cpp
When the MCTP daemon) closes the socket, the event loop may still deliver `EPOLLIN` alongside `POLLHUP`. Previously, the callback did not explicitly check for `POLLHUP` before attempting to receive data via `recvMsg()`.
This led to a scenario where `recvMsg()` was called on a socket that had already been closed, causing undefined behavior or memory corruption (e.g., during buffer allocation or cleanup). While `recvMsg()` returned a failure code (`PLDM_REQUESTER_RECV_FAIL`), the subsequent call to `io.get_event().exit(0)` would result in a crash due to the corrupted state.
This change adds an early check for `POLLHUP` (and `POLLERR`) at the beginning of the IO callback and exits the event loop immediately when detected. This prevents any further I/O operations on a dead socket and ensures …
=> Fix crash when handling socket closure early

oem/ibm/libpldmresponder/file_io_type_dump.cpp
There is no separate PLDM type for MSBE dumps; BMC sends MSBE dumps (identified by IDs starting with '4') using the SBE PLDM dump type. MSBE dump offload is failing due to an additional OR operation with '0x30000000' for SBE types. This OR operation has been removed, as converting the decimal dump ID recieved from PHYP to hexadecimal yields the correct dump ID without modification.
Tested both SBE and MSBE dump offload and it is working as expected.
Test Results:
MSBE offload:
```
Apr 14 08:15:48 p10bmc pvm_dump_offload[9803]: Watch propertiesChanged object path (/xyz/openbmc_project/dump/system/entry/40000041)
Apr 14 08:15:48 p10bmc pvm_dump_offload[9803]: Queue enqueue dump (/xyz/openbmc_project/dump/system/entry/40000041) size of Q (0)
Apr 14 08:15:48 p10bmc pvm_dump_offload[9803]: …
```
=> oem-ibm: Fix MSBE dump offload issue

host-bmc/host_pdr_handler.cpp, host-bmc/host_pdr_handler.hpp, oem/ibm/libpldmresponder/oem_ibm_handler.cpp
The op-panel function enabling will be sent down from PHYP with a modify event after the PDR exchange in the normal poweron path. But after a Reset Reload the function bitmaps will be sent down from PHYP with a Added event. To trigger the panel app even during the added event (reset reload case) this change is made.
Tested: Triggered the functions using the paneltool and the functions are persisted post reset reload also.
Fixes: 689601
=> host-bmc: Fix in the panel flow for Reset Reload

oem/ibm/service_files/meson.build, oem/ibm/service_files/pldm-clear-dma.service
In the current state , the DMA infrastruture written in pldm is Non-blocking IO, but for NVRAM writes/reads pldm still relies on blocking IO as AIO for NVRAM writes cause corruption especially during chassis off path where the host goes down abruptly. Due to pldm operating in blocking mode there are cases where pldm hangs in read/write system calls due to multiple reasons like :
1. Stray DMA message in mctp buffer When DMA operations in progress with PHYP and it goes down abruptly, the DMA command of PHYP could be stored inside the mctp buffer and that can be delivered to Hostboot(which does not have pcie support) leading to a pldm hang.
2. PHYP crashes while a DMA transaction is in progress xdma driver on bmc does not have a way to know if host had gone down due to crash , so the …
=> New service the clear's the stray DMA transactions

host-bmc/host_pdr_handler.cpp, oem/ibm/libpldmresponder/file_io.cpp, requester/handler.hpp
Phyp copies the error log data to the XDMA memory and then it sends the `WriteFileByTypeFromMemory` to PLDM.  From PLDM side, setting the struct AspeedXdmaOp instructs DMA controller to copy the data to bmc side. Because of slow data copy, we have partial data in the BMC XDMA buffer. As we have mmapped the VGA memory to the length of the Pel, we fetch the exact length which contains partial data and remaining bytes as garbage.
To fix the issue, added a check to make sure that if the DMA data copy is completed successfuly before copying the pel data to temporary file.
Fixes: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=678010
=> oem-ibm: Invalid pel fix
